/* Everything the Code pages show lives here, not in the HTML. This file is
   plain data on purpose: webpack.config.js reads it too, to build one page per
   project, so it must not import images. Pictures are named by key and looked
   up in media.js (covers, marks) and images.js (the Drive screens, `shots`). */

export const intro = {
  index: "01",
  title: "Code",
  lead: "I write the logic myself, from an empty file, and I let AI handle the work I already know how to do.",
  body: [
    "Every project here is plain <strong>JavaScript, HTML and CSS</strong>, with no framework doing the thinking for me. Battleship's engine, the to-do storage, the linked list, the hash map, the self-balancing tree: I wrote all that logic <strong>by hand</strong>. It's slower, and that's the point: when I reach for React, I'll know exactly what it saves me from.",
    "I do use <strong>AI</strong>, and directing it well is part of the job now. But you can only direct what you understand, so one rule: <strong>the reasoning stays mine</strong>. AI gets the repetitive work I've already done by hand many times, and I read everything it returns. Structure, algorithms and where the logic lives, I work out myself.",
  ],
};

export const GH = "https://github.com/AndreaGarzoglio/";
const PAGES = "https://andreagarzoglio.github.io/";

/* In the order they are shown. `practice` marks the algorithm and
   data-structure exercises, which get their own, quieter shelf. */
export const projects = [
  {
    id: "game-vault",
    // Every project has its own colour: its page's theme, and on the Code
    // overview the colour of its card.
    hue: "#a855f7",
    when: "Jan - Sep 2026",
    origin: "Began as the Library project",
    title: "Game Vault",
    tagline: "A tracker for the games I've played and the ones I mean to.",
    lead: "Rate games across several aspects, sort them into tier lists, import titles from <strong>IGDB</strong>. A small server of its own keeps the key safe, so it runs on Vercel.",
    repo: `${GH}game-vault`,
    live: "https://game-vault-andreagarzoglio.vercel.app/",
    shots: "code/game-vault",
    screens: [
      ["game-vault-library", "Library",
        "Every game in the vault as a card: cover, genre, scores and status. Search and sort run across the whole shelf."],
      ["game-vault-focus", "Focus",
        "A game opened up: description, a slider per aspect, my review, and related games from IGDB."],
      ["game-vault-about", "About",
        "An About me board: a topic on every card, from favourite villain to best soundtrack, and the game that answers it."],
      ["game-vault-tier", "Tier maker",
        "Covers dragged from the tray into ranked rows. Each tier list is saved and can be picked up again later."],
      ["game-vault-top", "Top list",
        "A ranked top ten, with a few lines on each pick, exportable as an image."],
    ],
    shows: ["Working with a REST API", "Keeping an API key server-side", "Data modelling", "Interface design"],
    stack: ["JavaScript ES6", "Node.js", "IGDB API", "REST"],
    notes: [
      ["What it does",
        "Game Vault tracks the games I've played and the ones I mean to. Each has a <strong>status</strong>, a favourite flag, tags and collections, all searchable. Adding a title fetches description, cover, genre and developer from <strong>IGDB</strong>, and a whole list can be pasted in at once."],
      ["Rating across aspects",
        "A single score never says what was actually good. Each game is rated on <strong>gameplay, story, graphics, music and enjoyment</strong>, plus any aspect I add, and the score is their average. Unrated games get their own section, ready to rate next."],
      ["One library, four views",
        "The same library feeds three more views: a <strong>tier maker</strong>, an About me wall where each prompt is answered by a game, and top lists of up to a hundred games. Each one exports as a PNG, and a game's page links to every place it appears."],
      ["Why there is a server",
        "IGDB needs an <strong>API key</strong>, and a key in front-end code is a key given away. IGDB also refuses browser calls, so a small <strong>server</strong> holds the key and passes results on: a Node script locally, a Vercel function online. Everything else stays in localStorage and exports as one JSON file."],
      ["No dependencies",
        "Plain HTML, CSS and JavaScript in ordinary script tags, <strong>no bundler</strong>. The server uses only Node's built-in modules, and the one outside script is html2canvas, for image export."],
    ],
  },
  {
    id: "battleship",
    hue: "#6366f1",
    when: "Aug - Sep 2026",
    origin: "Final JavaScript project",
    title: "Battleship",
    tagline: "Classic naval rules staged as a network intrusion.",
    lead: "The game logic is separate from the DOM, so it was built and <strong>tested</strong> before any interface, then wired to three modes: against the computer, two players on one screen, or computer against computer.",
    repo: `${GH}Battleship`,
    live: `${PAGES}Battleship/`,
    shots: "code/battleship-exe",
    screens: [
      ["battleship-01-start", "Start",
        "The intrusion brief sets the scene, then you choose who plays each side: a person or the computer."],
      ["battleship-02-placement", "Placement",
        "The fleet goes down one ship at a time, with a preview of where the next lands, while the operator comments."],
      ["battleship-03-gameplay", "Battle",
        "Your board on the left, the enemy's on the right: hits turn red, misses leave a dot, and both sides trade lines."],
      ["battleship-04-win", "Win",
        "Every enemy ship sunk. The game names the winner and offers a rematch."],
    ],
    shows: ["Logic kept apart from the DOM", "Unit tests with Jest", "A computer opponent that hunts", "A themed interface"],
    stack: ["JavaScript ES6", "Webpack", "Jest", "GitHub Pages"],
    notes: [
      ["Why the logic comes first",
        "The point is <strong>architecture</strong>: the game must work before any interface exists. Ships, boards, players and turns never touch the page, and the UI imports from the game, never the reverse. That made three modes easy: the computer playing itself is the same engine with a different caller."],
      ["Tested before it was visible",
        "Placement, hits, sinking, victory and the computer's hunting are covered by <strong>56 Jest tests</strong>, most passing before the first square was drawn."],
      ["Three modes, one opponent that hunts",
        "Play the computer, a friend on the same device, or watch two computers, one turn per click. The computer fires at random until it hits, then <strong>hunts</strong> along the line until the ship sinks."],
      ["Placing the fleet",
        "Ships are dragged from a dock, clicked to rotate and dragged again to move. An illegal drop is refused, with a visual hint why."],
      ["The intrusion",
        "Two characters comment on every move in a typed terminal voice, over <strong>Matrix-style rain</strong>, CRT scanlines and a glow that follows the turn. Everything stays still for anyone who asked for reduced motion."],
      ["Who wrote what",
        "The logic and its tests are <strong>mine</strong>, pseudocode and tests first, with an LLM only to check my reasoning. The visuals got much heavier LLM help, on purpose: the logic was the skill being tested, and the visuals were a chance to see how far I could <strong>direct a tool</strong> while judging its output."],
    ],
  },
  {
    id: "todo-list",
    hue: "#c0503c",
    when: "Mar - Sep 2026",
    origin: "Began as the Todo List project",
    title: "Todo List",
    tagline: "A to-do list disguised as a classified archive.",
    lead: "Projects are drawers, tasks are case files you tag, photograph and stamp closed. Plain ES6 classes over localStorage, no framework.",
    repo: `${GH}to-do-list`,
    live: `${PAGES}to-do-list/`,
    shots: "code/b-d-a",
    screens: [
      ["bda-01-schermata-principale", "Archive",
        "Each project is a drawer: flick through its files, filter them by clearance or status, or search everything you've been avoiding."],
      ["bda-02-focus-task", "Case file",
        "A task opened as a case file: dates, clearance, a photo and a briefing, ready to stamp closed, amend, file or shred."],
      ["bda-03-calendario", "Calendar",
        "The same files laid out by deadline. Pick a day to see what is due on it."],
    ],
    shows: ["ES6 classes", "Persistence with localStorage", "Interface as fiction"],
    stack: ["JavaScript ES6", "Classes", "localStorage", "Webpack", "GitHub Pages"],
    notes: [
      ["The fiction is the interface",
        "A project is a drawer, a task a case file, finishing it means <strong>stamping it closed</strong>. None of it is decoration: it says what can be done before any label is read. The fiction lives in style and copy, the data underneath is an ordinary to-do list."],
      ["Three classes and a Proxy",
        "The state is three plain classes: Todo, Project and TodoApp. TodoApp sits behind a JavaScript <strong>Proxy</strong>, so any change saves to localStorage by itself, with no save call anywhere else. If storage runs out, a toast says so."],
      ["A drawer you can flip through",
        "Each drawer stacks its files one behind the other, smaller and fainter further back. The only state is <strong>one number per drawer</strong>: how far the pile has been flipped. The wheel walks the pile, the arrows change drawer, a click opens the front file."],
      ["The rest of the archive",
        "Auto-coloured tags, subtasks with progress bars, photos resized before storing, a colour per folder, a deadline calendar, search, JSON export and import, and <strong>undo</strong> instead of a confirm prompt."],
      ["One render for everything",
        "Every change rebuilds the active view <strong>from scratch</strong>. No diffing, no virtual DOM: a little redundant work, but the page can never fall out of step with the data."],
    ],
  },
  {
    id: "weather-report",
    hue: "#38bdf8",
    when: "May - Sep 2026",
    origin: "Began as the Weather App project",
    title: "Weather Report",
    tagline: "An hour-by-hour curve, an eight-day outlook, and a sky that matches.",
    lead: "Temperature curve and forecast for any city, over a photo from Wikipedia and a sky that animates with the weather, drawn in <strong>CSS</strong>.",
    repo: `${GH}Weather-Report`,
    live: `${PAGES}Weather-Report/`,
    shots: "code/weather-report",
    screens: [
      ["weather-report-cloudy", "New York",
        "The temperature now, the days ahead and an hour-by-hour curve, over a photo of the city pulled from Wikipedia."],
      ["weather-report-genova", "Genova",
        "The details under the forecast: feels like, humidity, wind and gusts, pressure, cloud cover, visibility, sunrise and sunset."],
      ["weather-report-night", "Tokyo at night",
        "After sunset the sky switches to night, with a moon for an icon and stars over the city."],
      ["weather-report-rain", "Vienna in the rain",
        "The sky animates the weather it is reporting. Here it rains, drawn in CSS rather than played from a video."],
    ],
    shows: ["Async data from two APIs", "Handling missing data", "CSS animation"],
    stack: ["JavaScript ES6", "REST APIs", "Wikipedia API", "CSS animation", "GitHub Pages"],
    notes: [
      ["What it shows",
        "Conditions now, an <strong>eight-day</strong> outlook and an hour-by-hour view for any city: pick a day and scrub its hours while a line traces the temperature. Below, the details, from feels like to sunset, in Celsius or Fahrenheit."],
      ["A sky made of CSS",
        "Every condition is a few elements moved by <strong>CSS keyframes</strong>: rain and snow fall at random speeds, clouds drift as blurred gradients, fog rises, storms add lightning. A day and night wash sits underneath, and the accent colour follows the forecast. It weighs a <strong>fraction of a video</strong> and fits any screen."],
      ["Two sources, one screen",
        "The forecast comes from Visual Crossing, the photo from Wikipedia's keyless summary endpoint. A name like New York can be a state, a city or a magazine, so an ambiguous answer is <strong>retried as a city</strong>, and every search survives one source coming back empty."],
      ["Icons drawn by hand",
        "Weather icons are a small set of hand-drawn <strong>SVG</strong> line drawings, in place of emoji."],
    ],
  },
  {
    id: "knight-travails",
    practice: true,
    hue: "#c56cff",
    title: "Knight Travails",
    tagline: "Click two squares and watch the knight take the shortest route.",
    lead: "The path comes from a <strong>breadth-first search</strong>, and the solver comes with an annotated copy of itself, readable from the page.",
    repo: `${GH}Knight-Travails`,
    live: `${PAGES}Knight-Travails/`,
    shots: "code/knights-travails",
    screens: [
      ["knight-travails-base", "Corner to corner",
        "Pick a start and an end and the knight takes the shortest route. Corner to corner takes six moves."],
      ["knight-travails-random", "Random",
        "Random picks two squares for you. Every search is logged with its path and the number of moves."],
    ],
    shows: ["Breadth-first search", "Explaining code in the interface"],
    stack: ["JavaScript ES6", "Breadth-first search", "Graphs", "GitHub Pages"],
    notes: [
      ["Why breadth-first",
        "The solver lists the up to eight L-shaped moves from a square, then searches outward <strong>one move at a time</strong>. All knight moves are equal, so the first time a square is reached is the shortest route: no weights, no heuristic, no second pass."],
      ["Driving the board",
        "Click a square to place the knight and another to send it: the path lights up and the knight hops along it, with the move count under the board. Coordinates can be typed too, or Random picks both squares."],
      ["The code is part of the page",
        "A <strong>how it works</strong> button opens a commented copy of the solver inside the app: the algorithm is what's on display, not the chessboard."],
      ["Room for the board",
        "On a phone the side panel folds into a drawer that opens from the bottom, so the board keeps the whole screen."],
    ],
  },
  {
    id: "binary-search-trees",
    practice: true,
    hue: "#9a7dff",
    title: "Binary Search Trees",
    tagline: "A balanced tree written from scratch, redrawing as you change it.",
    lead: "Insert, delete and watch the diagram rebuild. Commands are split between those that change the tree and those that only read it.",
    repo: `${GH}Binary-Search-Trees`,
    live: `${PAGES}Binary-Search-Trees/`,
    shots: "code/binary-search-trees",
    screens: [
      ["bst-01-initial", "Starting tree",
        "The tree drawn from its starting values. Insert, delete and query from the panels below, and the diagram redraws after every command."],
      ["bst-02-insert-many", "Unbalanced",
        "A run of inserts piles nodes down one side, and isBalanced() now answers false."],
      ["bst-03-rebalance", "Rebalanced",
        "rebalance() rebuilds the tree from its sorted values into an even shape, and the check comes back true."],
    ],
    shows: ["Recursion", "Self-balancing trees", "Live visualisation"],
    stack: ["JavaScript ES6", "Data structures", "Recursion", "GitHub Pages"],
    notes: [
      ["A tree that starts balanced",
        "Each node has a value and two children: smaller goes left, bigger goes right. That rule makes lookup, insert and delete cost the tree's <strong>height</strong>, not its width. Building from an array sorts and dedupes it, then takes the middle as each root, so the tree starts <strong>balanced</strong>."],
      ["Every operation",
        "Insert and delete keep the rule intact. Queries cover includes, height, depth and isBalanced, plus the four <strong>traversals</strong>. rebalance() reads the values back in order and rebuilds the tree."],
      ["Seeing the rebalance",
        "A balanced tree is hard to believe until you <strong>watch it happen</strong>. Nodes are laid out in order and joined by SVG lines, the diagram redraws after every command, and the tree survives a reload."],
      ["Readers and writers, kept apart",
        "Traversals and lookups can't modify the tree, insert, delete and rebalance can. Keeping the two <strong>apart</strong>, in code and in the panels, makes the structure easy to reason about. The classes are covered by Jest tests."],
    ],
  },
  {
    id: "hashmap-hashset",
    practice: true,
    hue: "#e45cf0",
    title: "HashMap · HashSet",
    tagline: "Two hash tables written from scratch, with a page to poke at them.",
    lead: "A HashMap for key-value pairs and a HashSet for keys alone, both written <strong>bucket by bucket</strong>. They grow past their load factor, and a small page shows the table reshaping.",
    repo: `${GH}HashMap-HashSet`,
    live: `${PAGES}HashMap-HashSet/`,
    shots: "code/hashmap-hashset",
    screens: [
      ["01-hashmap-list", "HashMap",
        "Key/value pairs set one by one. The header keeps count of entries, capacity and load factor."],
      ["02-hashmap-query", "HashMap queries",
        "get, has, length, keys, values and entries, with every answer logged at the bottom."],
      ["03-hashset-list", "HashSet",
        "The same buckets holding keys only: a HashSet cares whether a value is there, not what it maps to."],
      ["04-hashset-query", "HashSet queries",
        "Checking membership: has() is false for a name that was never added and true for one that was."],
    ],
    shows: ["Hashing and collisions", "Dynamic resizing", "Designing for data"],
    stack: ["JavaScript ES6", "Hashing", "Data structures", "GitHub Pages"],
    notes: [
      ["One base, two tables",
        "Both extend one <strong>HashTable</strong> class that owns buckets, hashing, key checks, length and load factor. They differ only in what a bucket holds: pairs or bare values. Collisions are handled by chaining."],
      ["Growing on purpose",
        "When the load factor passes <strong>0.75</strong>, capacity doubles and every entry is rehashed. The header shows count, capacity and load live, so the step can be watched."],
      ["Giving a data structure a face",
        "A hash table has no interface, so I <strong>designed one</strong>: a tab per structure, commands split into mutate and query, a box per entry and a log of every call. The question was the same as for any illustration: <strong>where should the eye land first?</strong>"],
      ["One key, one value",
        "Setting an existing key <strong>overwrites</strong> it, and the set ignores duplicates. Both are covered by Jest tests, and both tables survive a reload."],
    ],
  },
  {
    id: "linked-list",
    practice: true,
    hue: "#7f8cff",
    title: "Linked List",
    tagline: "A singly linked list you can insert into and rearrange.",
    lead: "A singly linked list written node by node, with every node and <strong>pointer</strong> drawn on the page, so rearranging it is something to watch.",
    repo: `${GH}Linked-List`,
    live: `${PAGES}Linked-List/`,
    shots: "code/linked-list",
    screens: [
      ["linked-list-list", "Building the list",
        "Values appended one at a time. The chain at the top redraws after each command and always ends in null."],
      ["linked-list-list-details", "Queries",
        "Asking the list about itself: at, contains, find index, size and tail, each answer logged at the bottom."],
    ],
    shows: ["Nodes and pointers", "Edge cases first"],
    stack: ["JavaScript ES6", "Data structures", "GitHub Pages"],
    notes: [
      ["Only the head",
        "Each node holds a value and a pointer to the next, or null. The list only knows its <strong>head</strong>, which is why prepend is instant and append has to walk. Size is counted by walking too, so no length field can drift."],
      ["Every operation",
        "Append, prepend, insert at an index, remove, pop, plus at, contains, find index, size and tail. An index out of range throws a <strong>RangeError</strong> instead of failing quietly."],
      ["Pointers you can see",
        "The state line prints the chain as it stands, ( a )-> ( b )-> null, redrawn after every command, so an insert shows exactly where the chain was <strong>cut and rejoined</strong>."],
      ["Where the bugs live",
        "Index zero, the last node, an empty list: almost all the work was in the <strong>edge cases</strong>, each covered by a Jest test before the interface existed."],
    ],
  },
];

export const toolbox = [
  ["Language", "JavaScript, ES6 modules and classes. HTML and CSS by hand, no UI framework."],
  ["Build", "Webpack and npm scripts, with Babel where the tests need it."],
  ["Testing", "Jest, on the logic that can be separated from the interface."],
  ["Quality", "ESLint and Prettier, run on commit through Husky hooks."],
  ["Data", "REST APIs, localStorage, and a small Node server when a key has to stay private."],
  ["Deploy", "GitHub Pages, published by a GitHub Actions workflow."],
];

/* The path so far, one stage per section of the curriculum. Every stage
   draws its own small timeline: a bar per part of the course and a dot per
   project, on an axis that runs from the stage's first day to its last.
   Dates are "YYYY-MM" (the 1st) or "YYYY-MM-DD". Projects sit on the day
   they were committed as done; the course parts between them are
   approximate. "today" follows the calendar. A project with a page here links to it,
   the rest link to their repository. */
const TOP = "https://www.theodinproject.com/paths/";

export const path = [
  {
    title: "Start of the journey",
    from: "2025-05",
    to: "2025-07",
    text: [
      "I started like many: a few <strong>Udemy</strong> courses, a folder of JavaScript exercises, and the feeling everyone else understood something I'd missed. Scared and confused, I kept going until I found <strong>The Odin Project</strong>.",
    ],
    tracks: [
      { name: "Udemy courses", from: "2025-05", to: "2025-07" },
      {
        name: "JavaScript exercises",
        from: "2025-05-20",
        to: "2025-07",
        points: [{ at: "2025-07", label: "Found The Odin Project", href: TOP }],
      },
    ],
  },
  {
    title: "Foundations",
    from: "2025-07",
    to: "2025-10-25",
    link: `${TOP}foundations/courses/foundations`,
    text: [
      "The Odin Project gave me what the courses hadn't: an <strong>order</strong>. One thing after another, at a sensible pace, with a project at the end of each section to prove I'd really learned it. For the first time the confusion had a shape, and a shape can be worked through.",
    ],
    tracks: [
      {
        name: "HTML Foundations",
        from: "2025-07",
        to: "2025-07-25",
        points: [{ at: "2025-07-25", label: "Recipes", repo: "odin-recipes" }],
      },
      {
        name: "CSS Foundations · Flexbox",
        from: "2025-07-25",
        to: "2025-08-27",
        points: [{ at: "2025-08-27", label: "Landing Page", repo: "landing-page" }],
      },
      {
        name: "JavaScript Basics",
        from: "2025-08-27",
        to: "2025-10-25",
        points: [
          { at: "2025-09-05", label: "Rock Paper Scissors", repo: "rock-paper-scissors" },
          { at: "2025-10-02", label: "Etch-a-Sketch", repo: "etch-a-sketch" },
          { at: "2025-10-25", label: "Calculator", repo: "calculator" },
        ],
      },
    ],
  },
  {
    title: "Intermediate HTML and CSS",
    from: "2025-10-25",
    to: "2026-01-21",
    link: `${TOP}full-stack-javascript/courses/intermediate-html-and-css`,
    text: [
      "Harder, and much more rewarding. Units, positioning, custom properties, forms, grid: here CSS became a <strong>way of thinking about layout</strong>. The final admin dashboard was the first thing I built that looked like a real product.",
    ],
    tracks: [
      { name: "Intermediate HTML", from: "2025-10-25", to: "2025-11-10" },
      { name: "Intermediate CSS", from: "2025-11-10", to: "2025-12-01" },
      {
        name: "Forms",
        from: "2025-12-01",
        to: "2025-12-16",
        points: [{ at: "2025-12-16", label: "Sign-up Form", repo: "sign-up-form" }],
      },
      {
        name: "Grid",
        from: "2025-12-16",
        to: "2026-01-21",
        points: [{ at: "2026-01-21", label: "Admin Dashboard", repo: "admin-dashboard" }],
      },
    ],
  },
  {
    title: "JavaScript",
    from: "2026-01-21",
    to: "2026-08-07",
    link: `${TOP}full-stack-javascript/courses/javascript`,
    text: [
      "This is where it got hard: classes, modules, webpack, async code, testing, recursion, data structures, for <strong>seven months</strong>. At times honestly demoralising, with days stuck on a single problem. But I knew it was part of the process, so I kept going, one project at a time. It's the part I'm <strong>proudest</strong> of.",
    ],
    tracks: [
      {
        name: "Organizing your code",
        from: "2026-01-21",
        to: "2026-03-21",
        points: [
          { at: "2026-01-28", label: "Library", project: "game-vault" },
          { at: "2026-02-20", label: "Tic Tac Toe", repo: "Tic-Tac-Toe" },
          { at: "2026-03-11", label: "Restaurant Page", repo: "restaurant-page" },
          { at: "2026-03-21", label: "Todo List", project: "todo-list" },
        ],
      },
      { name: "JavaScript in the real world", from: "2026-03-21", to: "2026-04-10" },
      {
        name: "Asynchronous JS and APIs",
        from: "2026-04-10",
        to: "2026-05-19",
        points: [{ at: "2026-05-19", label: "Weather App", project: "weather-report" }],
      },
      {
        name: "Testing",
        from: "2026-05-19",
        to: "2026-05-30",
        points: [{ at: "2026-05-22", label: "Testing Practice", repo: "testingPractice" }],
      },
      {
        name: "Computer science",
        from: "2026-05-30",
        to: "2026-06-27",
        points: [
          { at: "2026-05-30", label: "Recursion", repo: "Recursion" },
          { at: "2026-06-12", label: "Linked List", project: "linked-list" },
          { at: "2026-06-15", label: "HashMap", project: "hashmap-hashset" },
          { at: "2026-06-17", label: "Binary Search Trees", project: "binary-search-trees" },
          { at: "2026-06-27", label: "Knights Travails", project: "knight-travails" },
        ],
      },
      { name: "Intermediate Git", from: "2026-06-27", to: "2026-07-10" },
      {
        name: "Finishing up",
        from: "2026-07-10",
        to: "2026-08-07",
        points: [{ at: "2026-08-07", label: "Battleship", project: "battleship" }],
      },
    ],
  },
  {
    title: "Making them mine",
    from: "2026-08-07",
    to: "2026-09-17",
    text: [
      "Before moving on I rebuilt the projects into apps I'd actually use: a real interface, a theme and a small story for each. Here my years as an <strong>artist</strong> finally got to work: the library became Game Vault, the to-do list a bureau of classified files, the weather app got a sky of its own.",
    ],
    tracks: [
      {
        name: "Redesign and polish",
        from: "2026-08-07",
        to: "2026-09-17",
        points: [
          { at: "2026-08-22", label: "Weather Report", project: "weather-report" },
          { at: "2026-08-26", label: "B.D.A.", project: "todo-list" },
          { at: "2026-09-01", label: "Game Vault", project: "game-vault" },
          { at: "2026-09-17", label: "BATTLESHIP.EXE", project: "battleship" },
        ],
      },
    ],
  },
  {
    title: "Advanced HTML and CSS",
    from: "2026-09-17",
    to: "today",
    link: `${TOP}full-stack-javascript/courses/advanced-html-and-css`,
    ticks: ["2026-09-17", "2026-09-24"],
    text: [
      "Animation, accessibility and responsive design, the last pieces of CSS. The final project is a personal homepage, <strong>this site</strong>. It was meant to be one simple page, but I wanted to challenge myself and present my work in a way worth exploring, so it grew into a <strong>portfolio</strong> for everything I do.",
    ],
    tracks: [
      { name: "Animation", from: "2026-09-17", to: "2026-09-20" },
      { name: "Accessibility", from: "2026-09-20", to: "2026-09-24" },
      {
        name: "Responsive design",
        from: "2026-09-24",
        to: "today",
        points: [{ at: "today", label: "Homepage: this site", href: "index.html" }],
      },
    ],
  },
];

// What is left of the path, shown after it without dates.
export const nextUp = {
  text: "With React I'll finally see what a framework does for me, now that I've done it all by hand.",
  courses: ["React", "Databases", "NodeJS"],
};
