/* Everything the Code pages show lives here, not in the HTML. This file is
   plain data on purpose: webpack.config.js reads it too, to build one page per
   project, so it must not import images. Pictures are named by key and looked
   up in media.js (covers, marks) and images.js (the Drive screens, `shots`). */

export const intro = {
  index: "01",
  title: "Code",
  lead: "I write the logic myself, from an empty file, and I let AI handle the work I already know how to do.",
  body: [
    "Every project on this page is plain JavaScript, HTML and CSS. No framework, no UI library, no package doing the thinking for me. The game engine behind Battleship, the storage layer of the to-do list, the linked list, the hash map, the tree that rebalances itself: I wrote all of that logic by hand, line by line, from scratch. It is slower, and that is the point. I want to understand what every piece does before I let a tool do it for me, so that when I do reach for React I will know exactly what it is saving me from.",
    "I do use large language models, and I think learning to direct them well is part of the job now, especially on a team where speed matters. But you can only direct what you understand, so I keep one rule: the reasoning stays mine. I hand the AI the repetitive work I have already done by hand many times (boilerplate, renaming across files, formatting data, a first draft of tests I have already designed) and I read everything that comes back. The structure, the algorithms and the decisions about where the logic lives are things I work out myself. It makes me faster without making me dependent.",
  ],
};

export const GH = "https://github.com/AndreaGarzoglio/";
const PAGES = "https://andreagarzoglio.github.io/";

/* In the order they are shown. `practice` marks the algorithm and
   data-structure exercises, which get their own, quieter shelf. */
export const projects = [
  {
    id: "game-vault",
    // The four apps are shown as résumé-style cards, each in its own colour.
    hue: "#a855f7",
    when: "Jan - Sep 2026",
    origin: "Began as the Library project",
    title: "Game Vault",
    tagline: "A tracker for the games I've played and the ones I mean to.",
    lead: "Rate them across several aspects, sort them into tier lists, pull titles straight from the IGDB catalogue. The catalogue is reached through a small server of its own, so the live version runs on Vercel rather than GitHub Pages.",
    repo: `${GH}game-vault`,
    live: "https://game-vault-andreagarzoglio.vercel.app/",
    shots: "code/game-vault",
    screens: [
      ["game-vault-library", "Library",
        "Every game in the vault as a card: cover, genre, a score for each aspect and where it stands, playing or completed. Search and sort run across the whole shelf."],
      ["game-vault-focus", "Focus",
        "One game opened up: its description, a slider for each aspect, my review, and related games pulled live from IGDB by shared genres and tags."],
      ["game-vault-about", "About",
        "An About me board: a topic on every card, from favourite villain to best soundtrack, and the game that answers it."],
      ["game-vault-tier", "Tier maker",
        "Covers dragged from the tray into ranked rows. Each tier list is saved and can be picked up again later."],
      ["game-vault-top", "Top list",
        "A ranked top ten, with a few lines on why each game earned its place. The list can be exported as an image."],
    ],
    shows: ["Working with a REST API", "Keeping an API key server-side", "Data modelling", "Interface design"],
    stack: ["JavaScript ES6", "Node.js", "IGDB API", "REST"],
    notes: [
      ["What it does",
        "Game Vault keeps track of the games I have played and the ones I mean to. Each game has a status (backlog, playing or completed), a favourite flag, free tags and named collections, and the library can be searched and filtered by any of them. Adding a title looks it up on IGDB and fills in the description, cover, genre and developer, all still editable; a whole list of titles can be pasted in at once, and each one is looked up on its own."],
      ["Rating across aspects",
        "A single score out of ten never says what was actually good. Every game is rated on gameplay, story, graphics, music and enjoyment, plus any aspect I decide to add, and its score is the average of the ones I filled in. Games with no ratings yet get a section of their own, so there is always an obvious pile to rate next."],
      ["One library, four views",
        "The same library feeds three more views. The tier maker builds fully custom boards from a tray that searches my games first and IGDB second. About me is a wall of prompt cards, each answered by one game. Top lists rank up to a hundred games on any subject. Any of them can be saved as a PNG taken from the real layout on screen, and a game's detail view lists every place it is featured, with a jump to each one."],
      ["Why there is a server",
        "The IGDB catalogue needs an API key, and a key in front-end code is a key you have given away. IGDB also refuses calls made straight from a browser, so a static host could not reach it even with the key hidden. A small server holds the key, fetches its own access token and passes the results on: a Node script on my machine, a Vercel function online. Everything else, the library included, stays in the browser's localStorage and can be exported and imported as a single JSON file."],
      ["No dependencies",
        "The app is plain HTML, CSS and JavaScript loaded as ordinary script tags, with no bundler. The server uses only Node's built-in modules, and the one outside script is html2canvas, for the image export."],
    ],
  },
  {
    id: "battleship",
    hue: "#6366f1",
    when: "Aug - Sep 2026",
    origin: "Final JavaScript project",
    title: "Battleship",
    tagline: "Classic naval rules staged as a network intrusion.",
    lead: "The game logic lives entirely apart from the DOM, so it could be built and tested before any interface existed, then wired up to three modes: against the computer, hotseat, or the computer playing itself.",
    repo: `${GH}Battleship`,
    live: `${PAGES}Battleship/`,
    shots: "code/battleship-exe",
    screens: [
      ["battleship-01-start", "Start",
        "The intrusion brief sets the scene, then you choose who plays each side: a person or the computer."],
      ["battleship-02-placement", "Placement",
        "The fleet goes down one ship at a time, with a preview of where the next one will land. The operator in the corner comments as you build."],
      ["battleship-03-gameplay", "Battle",
        "Your board on the left, the enemy's on the right. Hits turn red, misses leave a dot, and both sides trade lines as the round goes on."],
      ["battleship-04-win", "Win",
        "Every enemy ship sunk. The game names the winner and offers a rematch."],
    ],
    shows: ["Logic kept apart from the DOM", "Unit tests with Jest", "A computer opponent that hunts", "A themed interface"],
    stack: ["JavaScript ES6", "Webpack", "Jest", "GitHub Pages"],
    notes: [
      ["Why the logic comes first",
        "The point of the assignment is architecture: the game has to work before any interface exists. Ships, boards, players and turns live in their own folder and never touch the page; everything that does lives in a UI layer that imports from the game, never the other way round. That separation is what made the three modes cheap: the computer playing itself is the same engine with a different caller."],
      ["Tested before it was visible",
        "Placement rules, hits, sinking, the win condition and the computer's hunting are covered by 56 Jest tests that run without a browser. Most of them were passing before the first square was drawn."],
      ["Three modes, one opponent that hunts",
        "Play against the computer, against a friend on the same device with each board hidden between turns, or watch two computers play, one turn per click so it can be followed. The computer fires at random until it hits, then tries the cells around the hit, follows the line it finds until the ship sinks, and goes back to searching."],
      ["Placing the fleet",
        "Ships are dragged from a dock, clicked to rotate and dragged again to move them. A drop that breaks the rules is refused, with visual feedback on why."],
      ["The intrusion",
        "Two characters comment on every hit, miss and sunken ship in a typed terminal voice, over matrix rain drawn on a canvas, CRT scanlines and a glow that follows whose turn it is. The animations stand still for anyone who has asked their system for reduced motion."],
      ["Who wrote what",
        "The game logic and its tests are mine, written pseudocode first and test first, with an LLM used to check my reasoning rather than to write the code. The visual layer, from the matrix rain to the dialogue, was built with much heavier LLM help, on purpose: the logic was the skill being tested, and the visuals were my chance to see how far I could direct a tool while still judging what it gave me."],
    ],
  },
  {
    id: "todo-list",
    hue: "#c0503c",
    when: "Mar - Sep 2026",
    origin: "Began as the Todo List project",
    title: "Todo List",
    tagline: "A to-do list disguised as a classified archive.",
    lead: "Projects are drawers, tasks are case files you tag, photograph and stamp closed. Plain ES6 classes over localStorage, no framework.",
    repo: `${GH}to-do-list`,
    live: `${PAGES}to-do-list/`,
    shots: "code/b-d-a",
    screens: [
      ["bda-01-schermata-principale", "Archive",
        "Each project is a drawer. Flick through its case files, filter them by clearance or status, or search everything you have been avoiding."],
      ["bda-02-focus-task", "Case file",
        "A task opened as a case file: dates, clearance, a photo and a briefing. From here you stamp it closed, amend it, put it back or shred it."],
      ["bda-03-calendario", "Calendar",
        "The same files laid out by deadline. Pick a day to see what is due on it."],
    ],
    shows: ["ES6 classes", "Persistence with localStorage", "Interface as fiction"],
    stack: ["JavaScript ES6", "Classes", "localStorage", "Webpack", "GitHub Pages"],
    notes: [
      ["The fiction is the interface",
        "A project is a drawer, a task is a case file, finishing it means stamping it closed, and opening it shows a dossier with a photo, a briefing, tags and objectives. None of that is decoration: it tells you what you can do before you read a label. The fiction lives entirely in the styling and the copy; the data underneath is an ordinary to-do list."],
      ["Three classes and a Proxy",
        "The state is three plain classes: a Todo with its dates, priority, tags, subtasks and photo, a Project that holds the todos, and a TodoApp that holds everything. TodoApp sits behind a JavaScript Proxy, so any change to it saves the archive to localStorage by itself, and there is no save call anywhere else. If storage runs out, a toast says so instead of failing silently."],
      ["A drawer you can flip through",
        "Each drawer shows its files stacked one behind the other. Every file is placed by its depth, smaller and fainter the further back it sits, and the only state kept is one number per drawer: how far the pile has been flipped. The wheel walks the pile, the arrows change drawer, and clicking the file at the front pulls it out into its dossier."],
      ["The rest of the archive",
        "Tags coloured automatically, subtasks with a progress bar, a photo resized in the browser before it is stored, a colour per folder, a monthly calendar of deadlines, search across titles, notes and tags, a JSON export and import, and an undo for deleted files instead of a confirm prompt."],
      ["One render for everything",
        "Every change rebuilds the active view from scratch. No diffing and no virtual DOM: it does some redundant work, but the page can never drift out of step with the data."],
    ],
  },
  {
    id: "weather-report",
    hue: "#38bdf8",
    when: "May - Sep 2026",
    origin: "Began as the Weather App project",
    title: "Weather Report",
    tagline: "An hour-by-hour curve, an eight-day outlook, and a sky that matches.",
    lead: "Search a city for its temperature curve and forecast, over a live photo of the place pulled from Wikipedia and a sky that animates to match the weather, drawn in CSS rather than video.",
    repo: `${GH}Weather-Report`,
    live: `${PAGES}Weather-Report/`,
    shots: "code/weather-report",
    screens: [
      ["weather-report-cloudy", "New York",
        "The temperature now, the days ahead and an hour-by-hour curve, over a photo of the city pulled from Wikipedia."],
      ["weather-report-genova", "Genova",
        "The details under the forecast: feels like, humidity, wind and gusts, pressure, cloud cover, visibility, sunrise and sunset."],
      ["weather-report-night", "Tokyo at night",
        "After sunset the sky switches to night, with a moon for an icon and stars over the city."],
      ["weather-report-rain", "Vienna in the rain",
        "The sky animates the weather it is reporting. Here it rains, drawn in CSS rather than played from a video."],
    ],
    shows: ["Async data from two APIs", "Handling missing data", "CSS animation"],
    stack: ["JavaScript ES6", "REST APIs", "Wikipedia API", "CSS animation", "GitHub Pages"],
    notes: [
      ["What it shows",
        "Search any city for the conditions now, an eight-day outlook and an hour-by-hour view: pick a day and scrub through its hours while a line traces the temperature. Below sits the detail grid: feels like, humidity, wind and gusts, chance of rain, pressure, cloud cover, visibility, sunrise and sunset, in Celsius or Fahrenheit."],
      ["A sky made of CSS",
        "Every condition is a handful of elements moved by CSS keyframes. Rain and snow are single particles falling at random speeds, clouds are blurred gradients drifting across, sun rays are one blurred conic gradient, fog rises from the bottom, and storms add lightning. A day and night wash sits underneath, with stars after sunset, and the accent colour of the whole interface shifts with the forecast: azure for clear skies, violet for storms. It costs a fraction of a video and scales to any screen."],
      ["Two sources, one screen",
        "The forecast comes from the Visual Crossing API and the photograph from Wikipedia's public summary endpoint, which needs no key. A name like New York can point to a state, a city or a magazine, so an ambiguous answer is retried once as a city. Every search still has to survive one of the two sources having nothing to give."],
      ["Icons drawn by hand",
        "The weather icons are a small set of line drawings in SVG, picked from the forecast's own icon field, in place of emoji."],
    ],
  },
  {
    id: "knight-travails",
    practice: true,
    title: "Knight Travails",
    tagline: "Click two squares and watch the knight take the shortest route.",
    lead: "The path is found with a breadth-first search, and the solver ships with an annotated copy of itself you can read from the page.",
    repo: `${GH}Knight-Travails`,
    live: `${PAGES}Knight-Travails/`,
    shots: "code/knights-travails",
    screens: [
      ["knight-travails-base", "Corner to corner",
        "Pick a start and an end square and the knight takes the shortest route between them, found with a breadth-first search. Corner to corner takes six moves."],
      ["knight-travails-random", "Random",
        "Random picks two squares for you. Every search is logged with its path and the number of moves."],
    ],
    shows: ["Breadth-first search", "Explaining code in the interface"],
    stack: ["JavaScript ES6", "Breadth-first search", "Graphs", "GitHub Pages"],
    notes: [
      ["Why breadth-first",
        "The solver lists the up to eight L-shaped moves a knight can make from a square without leaving the board, then searches outward one move at a time. A knight's moves are all the same length, so the first time the search reaches a square it has reached it by the shortest route: no weighting, no heuristic, no second pass. The answer comes back as the path, square by square."],
      ["Driving the board",
        "Click a square to place the knight and another to send it there: the path lights up and the knight hops along it one move at a time, with the count shown under the board and in the log. The same works by typing coordinates, or by letting random pick both squares."],
      ["The code is part of the page",
        "A how it works button opens a commented copy of the solver without leaving the app, which is the point: the algorithm is the thing on display, not the chessboard."],
      ["Room for the board",
        "On a phone the side panel folds into a drawer that opens from the bottom, so the board keeps the whole screen."],
    ],
  },
  {
    id: "binary-search-trees",
    practice: true,
    title: "Binary Search Trees",
    tagline: "A balanced tree written from scratch, redrawing as you change it.",
    lead: "Insert and delete and watch the diagram rebuild. Commands are split between the ones that change the tree and the ones that only read it.",
    repo: `${GH}Binary-Search-Trees`,
    live: `${PAGES}Binary-Search-Trees/`,
    shots: "code/binary-search-trees",
    screens: [
      ["bst-01-initial", "Starting tree",
        "The tree drawn from its starting values. Insert, delete and query from the panels below, and the diagram redraws after every command."],
      ["bst-02-insert-many", "Unbalanced",
        "A run of inserts piles nodes down one side, and isBalanced() now answers false."],
      ["bst-03-rebalance", "Rebalanced",
        "rebalance() rebuilds the tree from its sorted values into an even shape, and the check comes back true."],
    ],
    shows: ["Recursion", "Self-balancing trees", "Live visualisation"],
    stack: ["JavaScript ES6", "Data structures", "Recursion", "GitHub Pages"],
    notes: [
      ["A tree that starts balanced",
        "Each node holds a value and a left and right child: everything smaller goes left, everything bigger goes right. That rule is what makes lookup, insert and delete take as long as the tree is tall rather than as long as it is wide. Building from an array sorts and dedupes it, then picks the middle value as the root of every subtree, so the tree starts out balanced."],
      ["Every operation",
        "Insert and delete keep the rule intact; deleting a node with two children swaps in the next value in order. Queries cover includes, height, depth and isBalanced, plus the four traversals: level order, in order, pre order and post order. rebalance() reads the values back in order and builds the tree again."],
      ["Seeing the rebalance",
        "A balanced tree is hard to believe in until you watch it happen. Nodes are laid out by an in-order pass, so left children always stay on the left, joined by SVG lines, and the diagram is redrawn after every command. The log at the bottom keeps the latest commands and errors, and the tree survives a reload."],
      ["Readers and writers, kept apart",
        "Traversals and lookups cannot modify the tree; insert, delete and rebalance can. Keeping the two sets separate, in the code and in the two panels, is what makes the structure safe to reason about. The classes are covered by Jest tests, and a commented copy of them opens from the how it works button."],
    ],
  },
  {
    id: "hashmap-hashset",
    practice: true,
    title: "HashMap · HashSet",
    tagline: "Two hash tables written from scratch, with a page to poke at them.",
    lead: "A HashMap that stores key-value pairs and a HashSet that only cares whether a key is there, both written bucket by bucket. They grow when the load factor passes its threshold, and a small page lets you add, remove and look things up while the table reshapes itself.",
    repo: `${GH}HashMap-HashSet`,
    live: `${PAGES}HashMap-HashSet/`,
    shots: "code/hashmap-hashset",
    screens: [
      ["01-hashmap-list", "HashMap",
        "Key/value pairs set one by one. The header keeps count of entries, capacity and load factor."],
      ["02-hashmap-query", "HashMap queries",
        "get, has, length, keys, values and entries, with every answer logged at the bottom."],
      ["03-hashset-list", "HashSet",
        "The same buckets holding keys only: a HashSet cares whether a value is there, not what it maps to."],
      ["04-hashset-query", "HashSet queries",
        "Checking membership: has() is false for a name that was never added and true for one that was."],
    ],
    shows: ["Hashing and collisions", "Dynamic resizing", "Designing for data"],
    stack: ["JavaScript ES6", "Hashing", "Data structures", "GitHub Pages"],
    notes: [
      ["One base, two tables",
        "HashMap and HashSet both extend one HashTable class that owns the buckets, the hash function, key checks, length, the load factor and clear. The two differ only in what a bucket holds: pairs for the map, bare values for the set. Collisions are handled by chaining, with several entries sharing a bucket."],
      ["Growing on purpose",
        "When the load factor, entries divided by capacity, goes past 0.75, the capacity doubles and every entry is hashed again into the new buckets. The header above the entries shows count, capacity and load live, so the step can be watched as it happens."],
      ["Giving a data structure a face",
        "A hash table has no interface of its own, so I designed one: a tab for each structure, commands split into mutate and query, one box per entry updated after every command, and a log that keeps every call and every error. The design question was the same as for any illustration: what should the eye land on first? A how it works button opens the source with comments on hashing, collisions and resizing, line by line."],
      ["One key, one value",
        "Setting a key that already exists overwrites its value instead of adding a second entry, and the set ignores a value it already holds. Both behaviours are covered by Jest tests, and both tables survive a reload."],
    ],
  },
  {
    id: "linked-list",
    practice: true,
    title: "Linked List",
    tagline: "A singly linked list you can insert into and rearrange.",
    lead: "A singly linked list written node by node: append, prepend, insert at an index, remove, find. The page draws every node and every pointer, so rearranging the list is something you watch rather than something you log.",
    repo: `${GH}Linked-List`,
    live: `${PAGES}Linked-List/`,
    shots: "code/linked-list",
    screens: [
      ["linked-list-list", "Building the list",
        "Values appended one at a time. The chain at the top redraws after each command and always ends in null."],
      ["linked-list-list-details", "Queries",
        "Asking the list about itself: at, contains, find index, size and tail, each answer logged at the bottom."],
    ],
    shows: ["Nodes and pointers", "Edge cases first"],
    stack: ["JavaScript ES6", "Data structures", "GitHub Pages"],
    notes: [
      ["Only the head",
        "Each node holds a value and a pointer to the next one, or null at the end. The list itself only knows its head, and every other node is reached by following the pointers, which is why prepend is instant and append has to walk. Size is counted by walking too, so there is no length field that could drift out of step."],
      ["Every operation",
        "Append, prepend, insert one or more values at an index, remove at an index and pop the head; then at, contains, find index, size and tail to ask it questions. An index out of range throws a RangeError instead of quietly doing nothing."],
      ["Pointers you can see",
        "The state line at the top prints the chain as it stands, ( a )-> ( b )-> null, and is redrawn after every command, so an insert in the middle shows exactly where the chain was cut and joined again. The log keeps each call with its answer, and a how it works modal explains how every method walks or rewires the chain."],
      ["Where the bugs live",
        "Inserting at index zero, removing the last node, searching an empty list: almost all of the work was in the edges, and each edge case was covered by a Jest test before the interface existed."],
    ],
  },
];

export const toolbox = [
  ["Language", "JavaScript, ES6 modules and classes. HTML and CSS by hand, no UI framework."],
  ["Build", "Webpack and npm scripts, with Babel where the tests need it."],
  ["Testing", "Jest, on the logic that can be separated from the interface."],
  ["Quality", "ESLint and Prettier, run on commit through Husky hooks."],
  ["Data", "REST APIs, localStorage, and a small Node server when a key has to stay private."],
  ["Deploy", "GitHub Pages, published by a GitHub Actions workflow."],
];

/* The path so far, one stage per section of the curriculum. Every stage
   draws its own small timeline: a bar per part of the course and a dot per
   project, on an axis that runs from the stage's first day to its last.
   Dates are "YYYY-MM" (the 1st) or "YYYY-MM-DD". Projects sit on the day
   they were committed as done; the course parts between them are
   approximate. "today" follows the calendar. A project with a page here links to it,
   the rest link to their repository. */
const TOP = "https://www.theodinproject.com/paths/";

export const path = [
  {
    title: "Start of the journey",
    from: "2025-05",
    to: "2025-07",
    text: [
      "I started the way a lot of people do: a few Udemy courses, a folder full of JavaScript exercises, and the constant feeling that everybody else had understood something I had missed. I learned the theory and did the exercises, scared and confused by nearly all of it, until I found The Odin Project.",
    ],
    tracks: [
      { name: "Udemy courses", from: "2025-05", to: "2025-07" },
      {
        name: "JavaScript exercises",
        from: "2025-05-20",
        to: "2025-07",
        points: [{ at: "2025-07", label: "Found The Odin Project", href: TOP }],
      },
    ],
  },
  {
    title: "Foundations",
    from: "2025-07",
    to: "2025-10-25",
    link: `${TOP}foundations/courses/foundations`,
    text: [
      "The Odin Project gave me what the courses had not: an order. One thing, then the next, at a pace that made sense, with a project at the end of every section to prove I had actually learned it rather than just read it. For the first time the confusion had a shape, and a shape is something you can work through.",
    ],
    tracks: [
      {
        name: "HTML Foundations",
        from: "2025-07",
        to: "2025-07-25",
        points: [{ at: "2025-07-25", label: "Recipes", repo: "odin-recipes" }],
      },
      {
        name: "CSS Foundations · Flexbox",
        from: "2025-07-25",
        to: "2025-08-27",
        points: [{ at: "2025-08-27", label: "Landing Page", repo: "landing-page" }],
      },
      {
        name: "JavaScript Basics",
        from: "2025-08-27",
        to: "2025-10-25",
        points: [
          { at: "2025-09-05", label: "Rock Paper Scissors", repo: "rock-paper-scissors" },
          { at: "2025-10-02", label: "Etch-a-Sketch", repo: "etch-a-sketch" },
          { at: "2025-10-25", label: "Calculator", repo: "calculator" },
        ],
      },
    ],
  },
  {
    title: "Intermediate HTML and CSS",
    from: "2025-10-25",
    to: "2026-01-21",
    link: `${TOP}full-stack-javascript/courses/intermediate-html-and-css`,
    text: [
      "More complex, and much more rewarding. Units, positioning, custom properties, forms, grid: this is where CSS stopped being a list of properties to remember and became a way of thinking about layout. The admin dashboard at the end was the first thing I built that looked like a real product.",
    ],
    tracks: [
      { name: "Intermediate HTML", from: "2025-10-25", to: "2025-11-10" },
      { name: "Intermediate CSS", from: "2025-11-10", to: "2025-12-01" },
      {
        name: "Forms",
        from: "2025-12-01",
        to: "2025-12-16",
        points: [{ at: "2025-12-16", label: "Sign-up Form", repo: "sign-up-form" }],
      },
      {
        name: "Grid",
        from: "2025-12-16",
        to: "2026-01-21",
        points: [{ at: "2026-01-21", label: "Admin Dashboard", repo: "admin-dashboard" }],
      },
    ],
  },
  {
    title: "JavaScript",
    from: "2026-01-21",
    to: "2026-08-07",
    link: `${TOP}full-stack-javascript/courses/javascript`,
    text: [
      "Then the difficulty spiked, hard. Objects and classes, modules and webpack, asynchronous code, testing, recursion, data structures, one after the other. For seven months it was extremely complex and at times demoralising, and more than once I was stuck on a single problem for days. I knew that was part of the process, so I persevered, one project at a time, and it is the part of this path I am proudest of.",
    ],
    tracks: [
      {
        name: "Organizing your code",
        from: "2026-01-21",
        to: "2026-03-21",
        points: [
          { at: "2026-01-28", label: "Library", project: "game-vault" },
          { at: "2026-02-20", label: "Tic Tac Toe", repo: "Tic-Tac-Toe" },
          { at: "2026-03-11", label: "Restaurant Page", repo: "restaurant-page" },
          { at: "2026-03-21", label: "Todo List", project: "todo-list" },
        ],
      },
      { name: "JavaScript in the real world", from: "2026-03-21", to: "2026-04-10" },
      {
        name: "Asynchronous JS and APIs",
        from: "2026-04-10",
        to: "2026-05-19",
        points: [{ at: "2026-05-19", label: "Weather App", project: "weather-report" }],
      },
      {
        name: "Testing",
        from: "2026-05-19",
        to: "2026-05-30",
        points: [{ at: "2026-05-22", label: "Testing Practice", repo: "testingPractice" }],
      },
      {
        name: "Computer science",
        from: "2026-05-30",
        to: "2026-06-27",
        points: [
          { at: "2026-05-30", label: "Recursion", repo: "Recursion" },
          { at: "2026-06-12", label: "Linked List", project: "linked-list" },
          { at: "2026-06-15", label: "HashMap", project: "hashmap-hashset" },
          { at: "2026-06-17", label: "Binary Search Trees", project: "binary-search-trees" },
          { at: "2026-06-27", label: "Knights Travails", project: "knight-travails" },
        ],
      },
      { name: "Intermediate Git", from: "2026-06-27", to: "2026-07-10" },
      {
        name: "Finishing up",
        from: "2026-07-10",
        to: "2026-08-07",
        points: [{ at: "2026-08-07", label: "Battleship", project: "battleship" }],
      },
    ],
  },
  {
    title: "Making them mine",
    from: "2026-08-07",
    to: "2026-09-17",
    text: [
      "Before moving on I went back to the projects and rebuilt them into apps I would actually want to use: a real interface, a theme and a small story for each one, and the fixes I had kept putting off. This is where my years as an artist and media designer finally got to do their job. The library became Game Vault, the to-do list became a bureau of classified files, the weather app got a sky of its own.",
    ],
    tracks: [
      {
        name: "Redesign and polish",
        from: "2026-08-07",
        to: "2026-09-17",
        points: [
          { at: "2026-08-22", label: "Weather Report", project: "weather-report" },
          { at: "2026-08-26", label: "B.D.A.", project: "todo-list" },
          { at: "2026-09-01", label: "Game Vault", project: "game-vault" },
          { at: "2026-09-17", label: "BATTLESHIP.EXE", project: "battleship" },
        ],
      },
    ],
  },
  {
    title: "Advanced HTML and CSS",
    from: "2026-09-17",
    to: "today",
    link: `${TOP}full-stack-javascript/courses/advanced-html-and-css`,
    ticks: ["2026-09-17", "2026-09-24"],
    text: [
      "Animation, accessibility and responsive design, the last pieces of CSS I was missing. The project that closes this course is a personal homepage, and you are looking at it: this site is that project, grown into a portfolio for everything I do.",
    ],
    tracks: [
      { name: "Animation", from: "2026-09-17", to: "2026-09-20" },
      { name: "Accessibility", from: "2026-09-20", to: "2026-09-24" },
      {
        name: "Responsive design",
        from: "2026-09-24",
        to: "today",
        points: [{ at: "today", label: "Homepage: this site", href: "index.html" }],
      },
    ],
  },
];

// What is left of the path, shown after it without dates.
export const nextUp = {
  text: "React is where I will finally find out what a framework does for me, now that I have done all of it by hand.",
  courses: ["React", "Databases", "NodeJS"],
};
