// Generated by scripts/build-images.py from raw/. Do not edit by hand.
import t0 from "../assets/work/art/msr/blackhat/blackhat-t.webp";
import f0 from "../assets/work/art/msr/blackhat/blackhat-f.webp";
import t1 from "../assets/work/art/msr/blackhat/blackhat-details-t.webp";
import f1 from "../assets/work/art/msr/blackhat/blackhat-details-f.webp";
import t2 from "../assets/work/art/msr/blackhat/blackhat-face-t.webp";
import f2 from "../assets/work/art/msr/blackhat/blackhat-face-f.webp";
import t3 from "../assets/work/art/msr/greyhat/greyhat-t.webp";
import f3 from "../assets/work/art/msr/greyhat/greyhat-f.webp";
import t4 from "../assets/work/art/msr/greyhat/greyhat-details-t.webp";
import f4 from "../assets/work/art/msr/greyhat/greyhat-details-f.webp";
import t5 from "../assets/work/art/msr/greyhat/greyhat-face-t.webp";
import f5 from "../assets/work/art/msr/greyhat/greyhat-face-f.webp";
import t6 from "../assets/work/art/msr/presentation/msr-the-hat-hackers-rw-1-t.webp";
import f6 from "../assets/work/art/msr/presentation/msr-the-hat-hackers-rw-1-f.webp";
import t7 from "../assets/work/art/msr/presentation/msr-the-hat-hackers-rw-2-t.webp";
import f7 from "../assets/work/art/msr/presentation/msr-the-hat-hackers-rw-2-f.webp";
import t8 from "../assets/work/art/msr/presentation/msr-the-hat-hackers-rw-3-t.webp";
import f8 from "../assets/work/art/msr/presentation/msr-the-hat-hackers-rw-3-f.webp";
import t9 from "../assets/work/art/msr/presentation/msr-the-hat-hackers-rw-4-t.webp";
import f9 from "../assets/work/art/msr/presentation/msr-the-hat-hackers-rw-4-f.webp";
import t10 from "../assets/work/art/msr/presentation/msr-the-hat-hackers-rw-5-t.webp";
import f10 from "../assets/work/art/msr/presentation/msr-the-hat-hackers-rw-5-f.webp";
import t11 from "../assets/work/art/msr/presentation/msr-the-hat-hackers-rw-6-t.webp";
import f11 from "../assets/work/art/msr/presentation/msr-the-hat-hackers-rw-6-f.webp";
import t12 from "../assets/work/art/msr/presentation/msr-the-hat-hackers-rw-7-t.webp";
import f12 from "../assets/work/art/msr/presentation/msr-the-hat-hackers-rw-7-f.webp";
import t13 from "../assets/work/art/msr/presentation/msr-the-hat-hackers-rw-8-t.webp";
import f13 from "../assets/work/art/msr/presentation/msr-the-hat-hackers-rw-8-f.webp";
import t14 from "../assets/work/art/msr/presentation/msr-the-hat-hackers-rw-9-t.webp";
import f14 from "../assets/work/art/msr/presentation/msr-the-hat-hackers-rw-9-f.webp";
import t15 from "../assets/work/art/msr/presentation/msr-the-hat-hackers-rw-10-t.webp";
import f15 from "../assets/work/art/msr/presentation/msr-the-hat-hackers-rw-10-f.webp";
import t16 from "../assets/work/art/msr/presentation/msr-the-hat-hackers-rw-11-t.webp";
import f16 from "../assets/work/art/msr/presentation/msr-the-hat-hackers-rw-11-f.webp";
import t17 from "../assets/work/art/msr/presentation/msr-the-hat-hackers-rw-12-t.webp";
import f17 from "../assets/work/art/msr/presentation/msr-the-hat-hackers-rw-12-f.webp";
import t18 from "../assets/work/art/msr/whitehat/whitehat-t.webp";
import f18 from "../assets/work/art/msr/whitehat/whitehat-f.webp";
import t19 from "../assets/work/art/msr/whitehat/whitehat-details-t.webp";
import f19 from "../assets/work/art/msr/whitehat/whitehat-details-f.webp";
import t20 from "../assets/work/art/msr/whitehat/whitehat-face-t.webp";
import f20 from "../assets/work/art/msr/whitehat/whitehat-face-f.webp";
import t21 from "../assets/work/art/nemixar/characters/tnbp-ninjasfin-t.webp";
import f21 from "../assets/work/art/nemixar/characters/tnbp-ninjasfin-f.webp";
import t22 from "../assets/work/art/nemixar/characters/tnsp-cassie-t.webp";
import f22 from "../assets/work/art/nemixar/characters/tnsp-cassie-f.webp";
import t23 from "../assets/work/art/nemixar/characters/tnsp-cpt-bonechuckle-t.webp";
import f23 from "../assets/work/art/nemixar/characters/tnsp-cpt-bonechuckle-f.webp";
import t24 from "../assets/work/art/nemixar/characters/tnsp-cunny-molly-t.webp";
import f24 from "../assets/work/art/nemixar/characters/tnsp-cunny-molly-f.webp";
import t25 from "../assets/work/art/nemixar/characters/tnsp-flashey-t.webp";
import f25 from "../assets/work/art/nemixar/characters/tnsp-flashey-f.webp";
import t26 from "../assets/work/art/nemixar/characters/tnsp-iappo-t.webp";
import f26 from "../assets/work/art/nemixar/characters/tnsp-iappo-f.webp";
import t27 from "../assets/work/art/nemixar/characters/tnsp-nyxia-t.webp";
import f27 from "../assets/work/art/nemixar/characters/tnsp-nyxia-f.webp";
import t28 from "../assets/work/art/nemixar/characters/tnsp-ramon-t.webp";
import f28 from "../assets/work/art/nemixar/characters/tnsp-ramon-f.webp";
import t29 from "../assets/work/art/nemixar/land-invasion/liguide-0-t.webp";
import f29 from "../assets/work/art/nemixar/land-invasion/liguide-0-f.webp";
import t30 from "../assets/work/art/nemixar/land-invasion/liguide-1-2-t.webp";
import f30 from "../assets/work/art/nemixar/land-invasion/liguide-1-2-f.webp";
import t31 from "../assets/work/art/nemixar/land-invasion/liguide-3-4-t.webp";
import f31 from "../assets/work/art/nemixar/land-invasion/liguide-3-4-f.webp";
import t32 from "../assets/work/art/nemixar/land-invasion/liguide-5-6-t.webp";
import f32 from "../assets/work/art/nemixar/land-invasion/liguide-5-6-f.webp";
import t33 from "../assets/work/art/nemixar/land-invasion/liguide-7-8-t.webp";
import f33 from "../assets/work/art/nemixar/land-invasion/liguide-7-8-f.webp";
import t34 from "../assets/work/art/personal-drawings/arcaster/arcaster-t.webp";
import f34 from "../assets/work/art/personal-drawings/arcaster/arcaster-f.webp";
import t35 from "../assets/work/art/personal-drawings/arcaster/arcaster-details-t.webp";
import f35 from "../assets/work/art/personal-drawings/arcaster/arcaster-details-f.webp";
import t36 from "../assets/work/art/personal-drawings/arcaster/arcaster-inspo-t.webp";
import f36 from "../assets/work/art/personal-drawings/arcaster/arcaster-inspo-f.webp";
import t37 from "../assets/work/art/personal-drawings/creature-study/arctic-predator-t.webp";
import f37 from "../assets/work/art/personal-drawings/creature-study/arctic-predator-f.webp";
import t38 from "../assets/work/art/personal-drawings/creature-study/arctic-prey-t.webp";
import f38 from "../assets/work/art/personal-drawings/creature-study/arctic-prey-f.webp";
import t39 from "../assets/work/art/personal-drawings/creature-study/chimeras-t.webp";
import f39 from "../assets/work/art/personal-drawings/creature-study/chimeras-f.webp";
import t40 from "../assets/work/art/personal-drawings/creature-study/choice-t.webp";
import f40 from "../assets/work/art/personal-drawings/creature-study/choice-f.webp";
import t41 from "../assets/work/art/personal-drawings/genista/genista-t.webp";
import f41 from "../assets/work/art/personal-drawings/genista/genista-f.webp";
import t42 from "../assets/work/art/personal-drawings/genista/genista-details-t.webp";
import f42 from "../assets/work/art/personal-drawings/genista/genista-details-f.webp";
import t43 from "../assets/work/art/personal-drawings/genista/genista-palettes-t.webp";
import f43 from "../assets/work/art/personal-drawings/genista/genista-palettes-f.webp";
import t44 from "../assets/work/art/personal-drawings/genista/genista-sketches-t.webp";
import f44 from "../assets/work/art/personal-drawings/genista/genista-sketches-f.webp";
import t45 from "../assets/work/art/personal-drawings/kurowo/kurowo-t.webp";
import f45 from "../assets/work/art/personal-drawings/kurowo/kurowo-f.webp";
import t46 from "../assets/work/art/personal-drawings/kurowo/kurowo-inspo-t.webp";
import f46 from "../assets/work/art/personal-drawings/kurowo/kurowo-inspo-f.webp";
import t47 from "../assets/work/art/personal-drawings/kurowo/kurowo-palettes-t.webp";
import f47 from "../assets/work/art/personal-drawings/kurowo/kurowo-palettes-f.webp";
import t48 from "../assets/work/art/personal-drawings/kurowo/kurowo-render-t.webp";
import f48 from "../assets/work/art/personal-drawings/kurowo/kurowo-render-f.webp";
import t49 from "../assets/work/art/personal-drawings/kurowo/kurowo-sketches-t.webp";
import f49 from "../assets/work/art/personal-drawings/kurowo/kurowo-sketches-f.webp";
import t50 from "../assets/work/art/personal-drawings/kurowo/kurowohouse-t.webp";
import f50 from "../assets/work/art/personal-drawings/kurowo/kurowohouse-f.webp";
import t51 from "../assets/work/art/personal-drawings/kurowo/kurowohouse-inspo-t.webp";
import f51 from "../assets/work/art/personal-drawings/kurowo/kurowohouse-inspo-f.webp";
import t52 from "../assets/work/art/personal-drawings/kurowo/kurowohouse-palettes-t.webp";
import f52 from "../assets/work/art/personal-drawings/kurowo/kurowohouse-palettes-f.webp";
import t53 from "../assets/work/art/personal-drawings/kurowo/kurowohouse-render-t.webp";
import f53 from "../assets/work/art/personal-drawings/kurowo/kurowohouse-render-f.webp";
import t54 from "../assets/work/art/personal-drawings/kurowo/kurowohouse-sketches-t.webp";
import f54 from "../assets/work/art/personal-drawings/kurowo/kurowohouse-sketches-f.webp";
import t55 from "../assets/work/art/personal-drawings/material-study/materials1-t.webp";
import f55 from "../assets/work/art/personal-drawings/material-study/materials1-f.webp";
import t56 from "../assets/work/art/personal-drawings/material-study/materials2-t.webp";
import f56 from "../assets/work/art/personal-drawings/material-study/materials2-f.webp";
import t57 from "../assets/work/art/personal-drawings/material-study/potion-t.webp";
import f57 from "../assets/work/art/personal-drawings/material-study/potion-f.webp";
import t58 from "../assets/work/art/personal-drawings/non/non-t.webp";
import f58 from "../assets/work/art/personal-drawings/non/non-f.webp";
import t59 from "../assets/work/art/personal-drawings/non/non-inspo-t.webp";
import f59 from "../assets/work/art/personal-drawings/non/non-inspo-f.webp";
import t60 from "../assets/work/art/personal-drawings/non/non-palettes-t.webp";
import f60 from "../assets/work/art/personal-drawings/non/non-palettes-f.webp";
import t61 from "../assets/work/art/personal-drawings/non/non-render-t.webp";
import f61 from "../assets/work/art/personal-drawings/non/non-render-f.webp";
import t62 from "../assets/work/art/personal-drawings/non/non-sketches-t.webp";
import f62 from "../assets/work/art/personal-drawings/non/non-sketches-f.webp";
import t63 from "../assets/work/art/personal-drawings/non/nonroom-t.webp";
import f63 from "../assets/work/art/personal-drawings/non/nonroom-f.webp";
import t64 from "../assets/work/art/personal-drawings/non/nonroom-cellshading-t.webp";
import f64 from "../assets/work/art/personal-drawings/non/nonroom-cellshading-f.webp";
import t65 from "../assets/work/art/personal-drawings/non/nonroom-inspo-t.webp";
import f65 from "../assets/work/art/personal-drawings/non/nonroom-inspo-f.webp";
import t66 from "../assets/work/art/personal-drawings/non/nonroom-palettes-t.webp";
import f66 from "../assets/work/art/personal-drawings/non/nonroom-palettes-f.webp";
import t67 from "../assets/work/art/personal-drawings/non/nonroom-sketch-t.webp";
import f67 from "../assets/work/art/personal-drawings/non/nonroom-sketch-f.webp";
import t68 from "../assets/work/art/personal-drawings/nora/nora-t.webp";
import f68 from "../assets/work/art/personal-drawings/nora/nora-f.webp";
import t69 from "../assets/work/art/personal-drawings/nora/nora-details-t.webp";
import f69 from "../assets/work/art/personal-drawings/nora/nora-details-f.webp";
import t70 from "../assets/work/art/personal-drawings/nora/nora-inspo-t.webp";
import f70 from "../assets/work/art/personal-drawings/nora/nora-inspo-f.webp";
import t71 from "../assets/work/art/personal-drawings/nora/nora-palettes-t.webp";
import f71 from "../assets/work/art/personal-drawings/nora/nora-palettes-f.webp";
import t72 from "../assets/work/art/personal-drawings/nora/nora-sketch-t.webp";
import f72 from "../assets/work/art/personal-drawings/nora/nora-sketch-f.webp";
import t73 from "../assets/work/art/personal-drawings/rendering-study/portrait-cartoon-t.webp";
import f73 from "../assets/work/art/personal-drawings/rendering-study/portrait-cartoon-f.webp";
import t74 from "../assets/work/art/personal-drawings/rendering-study/portrait-from-photo-t.webp";
import f74 from "../assets/work/art/personal-drawings/rendering-study/portrait-from-photo-f.webp";
import t75 from "../assets/work/art/personal-drawings/rendering-study/render-orc-1-t.webp";
import f75 from "../assets/work/art/personal-drawings/rendering-study/render-orc-1-f.webp";
import t76 from "../assets/work/art/personal-drawings/rendering-study/render-orc-2-t.webp";
import f76 from "../assets/work/art/personal-drawings/rendering-study/render-orc-2-f.webp";
import t77 from "../assets/work/art/personal-drawings/rendering-study/render-orc-3-t.webp";
import f77 from "../assets/work/art/personal-drawings/rendering-study/render-orc-3-f.webp";
import t78 from "../assets/work/art/personal-drawings/shading-study/face-shading-t.webp";
import f78 from "../assets/work/art/personal-drawings/shading-study/face-shading-f.webp";
import t79 from "../assets/work/art/personal-drawings/shading-study/lights1-t.webp";
import f79 from "../assets/work/art/personal-drawings/shading-study/lights1-f.webp";
import t80 from "../assets/work/art/personal-drawings/shading-study/lights2-t.webp";
import f80 from "../assets/work/art/personal-drawings/shading-study/lights2-f.webp";
import t81 from "../assets/work/art/personal-drawings/shading-study/lights3-t.webp";
import f81 from "../assets/work/art/personal-drawings/shading-study/lights3-f.webp";
import t82 from "../assets/work/art/personal-drawings/shading-study/shapes1-t.webp";
import f82 from "../assets/work/art/personal-drawings/shading-study/shapes1-f.webp";
import t83 from "../assets/work/art/personal-drawings/shading-study/shapes2-t.webp";
import f83 from "../assets/work/art/personal-drawings/shading-study/shapes2-f.webp";
import t84 from "../assets/work/art/personal-drawings/shading-study/shapes3-t.webp";
import f84 from "../assets/work/art/personal-drawings/shading-study/shapes3-f.webp";
import t85 from "../assets/work/art/personal-drawings/shading-study/shapes4-t.webp";
import f85 from "../assets/work/art/personal-drawings/shading-study/shapes4-f.webp";
import t86 from "../assets/work/art/personal-drawings/shading-study/shapes5-t.webp";
import f86 from "../assets/work/art/personal-drawings/shading-study/shapes5-f.webp";
import t87 from "../assets/work/art/ymdir/designs/boar-t.webp";
import f87 from "../assets/work/art/ymdir/designs/boar-f.webp";
import t88 from "../assets/work/art/ymdir/designs/kra-khom-t.webp";
import f88 from "../assets/work/art/ymdir/designs/kra-khom-f.webp";
import t89 from "../assets/work/art/ymdir/designs/kra-khom-ta-t.webp";
import f89 from "../assets/work/art/ymdir/designs/kra-khom-ta-f.webp";
import t90 from "../assets/work/art/ymdir/designs/props-t.webp";
import f90 from "../assets/work/art/ymdir/designs/props-f.webp";
import t91 from "../assets/work/art/ymdir/designs/wolf-t.webp";
import f91 from "../assets/work/art/ymdir/designs/wolf-f.webp";
import t92 from "../assets/work/art/ymdir/dice/copy-of-s-d-analyze-t.webp";
import f92 from "../assets/work/art/ymdir/dice/copy-of-s-d-analyze-f.webp";
import t93 from "../assets/work/art/ymdir/dice/copy-of-s-d-bidingtime-t.webp";
import f93 from "../assets/work/art/ymdir/dice/copy-of-s-d-bidingtime-f.webp";
import t94 from "../assets/work/art/ymdir/dice/copy-of-s-d-changeofplans-t.webp";
import f94 from "../assets/work/art/ymdir/dice/copy-of-s-d-changeofplans-f.webp";
import t95 from "../assets/work/art/ymdir/dice/copy-of-s-d-channel-t.webp";
import f95 from "../assets/work/art/ymdir/dice/copy-of-s-d-channel-f.webp";
import t96 from "../assets/work/art/ymdir/dice/copy-of-s-d-climax-t.webp";
import f96 from "../assets/work/art/ymdir/dice/copy-of-s-d-climax-f.webp";
import t97 from "../assets/work/art/ymdir/dice/copy-of-s-d-criticalstrike-t.webp";
import f97 from "../assets/work/art/ymdir/dice/copy-of-s-d-criticalstrike-f.webp";
import t98 from "../assets/work/art/ymdir/dice/copy-of-s-d-defensivestance-t.webp";
import f98 from "../assets/work/art/ymdir/dice/copy-of-s-d-defensivestance-f.webp";
import t99 from "../assets/work/art/ymdir/dice/copy-of-s-d-freezeburn-t.webp";
import f99 from "../assets/work/art/ymdir/dice/copy-of-s-d-freezeburn-f.webp";
import t100 from "../assets/work/art/ymdir/dice/copy-of-s-d-hunterssight-t.webp";
import f100 from "../assets/work/art/ymdir/dice/copy-of-s-d-hunterssight-f.webp";
import t101 from "../assets/work/art/ymdir/dice/copy-of-s-d-hunterssight-v2-t.webp";
import f101 from "../assets/work/art/ymdir/dice/copy-of-s-d-hunterssight-v2-f.webp";
import t102 from "../assets/work/art/ymdir/dice/copy-of-s-d-icebarrier-t.webp";
import f102 from "../assets/work/art/ymdir/dice/copy-of-s-d-icebarrier-f.webp";
import t103 from "../assets/work/art/ymdir/dice/copy-of-s-d-lacerate-t.webp";
import f103 from "../assets/work/art/ymdir/dice/copy-of-s-d-lacerate-f.webp";
import t104 from "../assets/work/art/ymdir/dice/copy-of-s-d-poke-t.webp";
import f104 from "../assets/work/art/ymdir/dice/copy-of-s-d-poke-f.webp";
import t105 from "../assets/work/art/ymdir/dice/copy-of-s-d-pummel-t.webp";
import f105 from "../assets/work/art/ymdir/dice/copy-of-s-d-pummel-f.webp";
import t106 from "../assets/work/art/ymdir/dice/copy-of-s-d-recklessstrike-t.webp";
import f106 from "../assets/work/art/ymdir/dice/copy-of-s-d-recklessstrike-f.webp";
import t107 from "../assets/work/art/ymdir/dice/copy-of-s-d-redirection-t.webp";
import f107 from "../assets/work/art/ymdir/dice/copy-of-s-d-redirection-f.webp";
import t108 from "../assets/work/art/ymdir/dice/copy-of-s-d-searingcut-t.webp";
import f108 from "../assets/work/art/ymdir/dice/copy-of-s-d-searingcut-f.webp";
import t109 from "../assets/work/art/ymdir/dice/copy-of-s-d-shield-t.webp";
import f109 from "../assets/work/art/ymdir/dice/copy-of-s-d-shield-f.webp";
import t110 from "../assets/work/art/ymdir/dice/copy-of-s-d-slice-t.webp";
import f110 from "../assets/work/art/ymdir/dice/copy-of-s-d-slice-f.webp";
import t111 from "../assets/work/art/ymdir/dice/copy-of-s-d-spectralblades-t.webp";
import f111 from "../assets/work/art/ymdir/dice/copy-of-s-d-spectralblades-f.webp";
import t112 from "../assets/work/art/ymdir/dice/copy-of-s-d-spikes-t.webp";
import f112 from "../assets/work/art/ymdir/dice/copy-of-s-d-spikes-f.webp";
import t113 from "../assets/work/art/ymdir/dice/copy-of-s-d-wisenedstrike-t.webp";
import f113 from "../assets/work/art/ymdir/dice/copy-of-s-d-wisenedstrike-f.webp";
import t114 from "../assets/work/art/ymdir/dice/copy-of-s-d-wrath-t.webp";
import f114 from "../assets/work/art/ymdir/dice/copy-of-s-d-wrath-f.webp";
import t115 from "../assets/work/art/ymdir/map-and-ui/map-ui-t.webp";
import f115 from "../assets/work/art/ymdir/map-and-ui/map-ui-f.webp";
import t116 from "../assets/work/art/ymdir/map-and-ui/ymdir-map-t.webp";
import f116 from "../assets/work/art/ymdir/map-and-ui/ymdir-map-f.webp";
import t117 from "../assets/work/art/ymdir/old-designs/bat-t.webp";
import f117 from "../assets/work/art/ymdir/old-designs/bat-f.webp";
import t118 from "../assets/work/art/ymdir/old-designs/bat-turnaround-t.webp";
import f118 from "../assets/work/art/ymdir/old-designs/bat-turnaround-f.webp";
import t119 from "../assets/work/art/ymdir/old-designs/beasts1-t.webp";
import f119 from "../assets/work/art/ymdir/old-designs/beasts1-f.webp";
import t120 from "../assets/work/art/ymdir/old-designs/beasts2-t.webp";
import f120 from "../assets/work/art/ymdir/old-designs/beasts2-f.webp";
import t121 from "../assets/work/art/ymdir/old-designs/beasts3-t.webp";
import f121 from "../assets/work/art/ymdir/old-designs/beasts3-f.webp";
import t122 from "../assets/work/art/ymdir/old-designs/beasts4-t.webp";
import f122 from "../assets/work/art/ymdir/old-designs/beasts4-f.webp";
import t123 from "../assets/work/art/ymdir/old-designs/beasts5-t.webp";
import f123 from "../assets/work/art/ymdir/old-designs/beasts5-f.webp";
import t124 from "../assets/work/art/ymdir/old-designs/beasts-ta-t.webp";
import f124 from "../assets/work/art/ymdir/old-designs/beasts-ta-f.webp";
import t125 from "../assets/work/art/ymdir/old-designs/big-bandit-t.webp";
import f125 from "../assets/work/art/ymdir/old-designs/big-bandit-f.webp";
import t126 from "../assets/work/art/ymdir/old-designs/blob-t.webp";
import f126 from "../assets/work/art/ymdir/old-designs/blob-f.webp";
import t127 from "../assets/work/art/ymdir/old-designs/blob-turn-t.webp";
import f127 from "../assets/work/art/ymdir/old-designs/blob-turn-f.webp";
import t128 from "../assets/work/art/ymdir/old-designs/golemboss-t.webp";
import f128 from "../assets/work/art/ymdir/old-designs/golemboss-f.webp";
import t129 from "../assets/work/art/ymdir/old-designs/great-wolf-new-t.webp";
import f129 from "../assets/work/art/ymdir/old-designs/great-wolf-new-f.webp";
import t130 from "../assets/work/art/ymdir/old-designs/kah-krom-t.webp";
import f130 from "../assets/work/art/ymdir/old-designs/kah-krom-f.webp";
import t131 from "../assets/work/art/ymdir/old-designs/logo-t.webp";
import f131 from "../assets/work/art/ymdir/old-designs/logo-f.webp";
import t132 from "../assets/work/art/ymdir/old-designs/lokyr-t.webp";
import f132 from "../assets/work/art/ymdir/old-designs/lokyr-f.webp";
import t133 from "../assets/work/art/ymdir/old-designs/mad-burger-logo-t.webp";
import f133 from "../assets/work/art/ymdir/old-designs/mad-burger-logo-f.webp";
import t134 from "../assets/work/art/ymdir/old-designs/riam-t.webp";
import f134 from "../assets/work/art/ymdir/old-designs/riam-f.webp";
import t135 from "../assets/work/art/ymdir/old-designs/riam0-t.webp";
import f135 from "../assets/work/art/ymdir/old-designs/riam0-f.webp";
import t136 from "../assets/work/art/ymdir/old-designs/riam2-t.webp";
import f136 from "../assets/work/art/ymdir/old-designs/riam2-f.webp";
import t137 from "../assets/work/art/ymdir/old-designs/riam3-t.webp";
import f137 from "../assets/work/art/ymdir/old-designs/riam3-f.webp";
import t138 from "../assets/work/art/ymdir/old-designs/riam4-t.webp";
import f138 from "../assets/work/art/ymdir/old-designs/riam4-f.webp";
import t139 from "../assets/work/art/ymdir/old-designs/riam-2-t.webp";
import f139 from "../assets/work/art/ymdir/old-designs/riam-2-f.webp";
import t140 from "../assets/work/art/ymdir/old-designs/riamthumbnail-t.webp";
import f140 from "../assets/work/art/ymdir/old-designs/riamthumbnail-f.webp";
import t141 from "../assets/work/art/ymdir/old-designs/rogue-t.webp";
import f141 from "../assets/work/art/ymdir/old-designs/rogue-f.webp";
import t142 from "../assets/work/art/ymdir/old-designs/rogue-2-t.webp";
import f142 from "../assets/work/art/ymdir/old-designs/rogue-2-f.webp";
import t143 from "../assets/work/art/ymdir/old-designs/rogueboss-t.webp";
import f143 from "../assets/work/art/ymdir/old-designs/rogueboss-f.webp";
import t144 from "../assets/work/art/ymdir/old-designs/sha-rah-harper-t.webp";
import f144 from "../assets/work/art/ymdir/old-designs/sha-rah-harper-f.webp";
import t145 from "../assets/work/art/ymdir/old-dice/copy-of-eternal-dice-nobg-t.webp";
import f145 from "../assets/work/art/ymdir/old-dice/copy-of-eternal-dice-nobg-f.webp";
import t146 from "../assets/work/art/ymdir/old-dice/copy-of-heavy-dice-nobg-t.webp";
import f146 from "../assets/work/art/ymdir/old-dice/copy-of-heavy-dice-nobg-f.webp";
import t147 from "../assets/work/art/ymdir/old-dice/copy-of-negative-dice-nobg-t.webp";
import f147 from "../assets/work/art/ymdir/old-dice/copy-of-negative-dice-nobg-f.webp";
import t148 from "../assets/work/art/ymdir/old-dice/copy-of-normal-dice-nobg-t.webp";
import f148 from "../assets/work/art/ymdir/old-dice/copy-of-normal-dice-nobg-f.webp";
import t149 from "../assets/work/art/ymdir/old-dice/copy-of-reckless-dice-nobg-t.webp";
import f149 from "../assets/work/art/ymdir/old-dice/copy-of-reckless-dice-nobg-f.webp";
import t150 from "../assets/work/art/ymdir/old-dice/copy-of-tombstone-dice-nobg-t.webp";
import f150 from "../assets/work/art/ymdir/old-dice/copy-of-tombstone-dice-nobg-f.webp";
import t151 from "../assets/work/art/ymdir/old-ui/old-icons-t.webp";
import f151 from "../assets/work/art/ymdir/old-ui/old-icons-f.webp";
import t152 from "../assets/work/art/ymdir/old-ui/vfx-att-debuff-t.webp";
import f152 from "../assets/work/art/ymdir/old-ui/vfx-att-debuff-f.webp";
import t153 from "../assets/work/art/ymdir/old-ui/vfx-berserk-t.webp";
import f153 from "../assets/work/art/ymdir/old-ui/vfx-berserk-f.webp";
import t154 from "../assets/work/art/ymdir/old-ui/vfx-berserk-and-frostbite-1-t.webp";
import f154 from "../assets/work/art/ymdir/old-ui/vfx-berserk-and-frostbite-1-f.webp";
import t155 from "../assets/work/art/ymdir/old-ui/vfx-buff-t.webp";
import f155 from "../assets/work/art/ymdir/old-ui/vfx-buff-f.webp";
import t156 from "../assets/work/art/ymdir/old-ui/vfx-def-t.webp";
import f156 from "../assets/work/art/ymdir/old-ui/vfx-def-f.webp";
import t157 from "../assets/work/art/ymdir/old-ui/vfx-def-debuff-t.webp";
import f157 from "../assets/work/art/ymdir/old-ui/vfx-def-debuff-f.webp";
import t158 from "../assets/work/art/ymdir/old-ui/vfx-frostbite-t.webp";
import f158 from "../assets/work/art/ymdir/old-ui/vfx-frostbite-f.webp";
import t159 from "../assets/work/art/ymdir/old-ui/vfx-heal-t.webp";
import f159 from "../assets/work/art/ymdir/old-ui/vfx-heal-f.webp";
import t160 from "../assets/work/art/ymdir/vfx/banditvfx-t.webp";
import f160 from "../assets/work/art/ymdir/vfx/banditvfx-f.webp";
import t161 from "../assets/work/art/ymdir/vfx/big-bandit-vfx-t.webp";
import f161 from "../assets/work/art/ymdir/vfx/big-bandit-vfx-f.webp";
import t162 from "../assets/work/art/ymdir/vfx/boar-vfx-t.webp";
import f162 from "../assets/work/art/ymdir/vfx/boar-vfx-f.webp";
import t163 from "../assets/work/art/ymdir/vfx/elemental-vfx-t.webp";
import f163 from "../assets/work/art/ymdir/vfx/elemental-vfx-f.webp";
import t164 from "../assets/work/art/ymdir/vfx/king-boar-vfx-t.webp";
import f164 from "../assets/work/art/ymdir/vfx/king-boar-vfx-f.webp";
import t165 from "../assets/work/art/ymdir/vfx/priest-vfx-t.webp";
import f165 from "../assets/work/art/ymdir/vfx/priest-vfx-f.webp";
import t166 from "../assets/work/art/ymdir/vfx/small-golem-vfx-t.webp";
import f166 from "../assets/work/art/ymdir/vfx/small-golem-vfx-f.webp";
import t167 from "../assets/work/art/ymdir/vfx/wolf-vfx-t.webp";
import f167 from "../assets/work/art/ymdir/vfx/wolf-vfx-f.webp";
import t168 from "../assets/work/art/ymdir/vfx/wyvern-memory-vfx-t.webp";
import f168 from "../assets/work/art/ymdir/vfx/wyvern-memory-vfx-f.webp";
import t169 from "../assets/work/code/b-d-a/bda-01-schermata-principale-t.webp";
import f169 from "../assets/work/code/b-d-a/bda-01-schermata-principale-f.webp";
import t170 from "../assets/work/code/b-d-a/bda-02-focus-task-t.webp";
import f170 from "../assets/work/code/b-d-a/bda-02-focus-task-f.webp";
import t171 from "../assets/work/code/b-d-a/bda-03-calendario-t.webp";
import f171 from "../assets/work/code/b-d-a/bda-03-calendario-f.webp";
import t172 from "../assets/work/code/battleship-exe/battleship-01-start-t.webp";
import f172 from "../assets/work/code/battleship-exe/battleship-01-start-f.webp";
import t173 from "../assets/work/code/battleship-exe/battleship-02-placement-t.webp";
import f173 from "../assets/work/code/battleship-exe/battleship-02-placement-f.webp";
import t174 from "../assets/work/code/battleship-exe/battleship-03-gameplay-t.webp";
import f174 from "../assets/work/code/battleship-exe/battleship-03-gameplay-f.webp";
import t175 from "../assets/work/code/battleship-exe/battleship-04-win-t.webp";
import f175 from "../assets/work/code/battleship-exe/battleship-04-win-f.webp";
import t176 from "../assets/work/code/binary-search-trees/bst-01-initial-t.webp";
import f176 from "../assets/work/code/binary-search-trees/bst-01-initial-f.webp";
import t177 from "../assets/work/code/binary-search-trees/bst-02-insert-many-t.webp";
import f177 from "../assets/work/code/binary-search-trees/bst-02-insert-many-f.webp";
import t178 from "../assets/work/code/binary-search-trees/bst-03-rebalance-t.webp";
import f178 from "../assets/work/code/binary-search-trees/bst-03-rebalance-f.webp";
import t179 from "../assets/work/code/game-vault/game-vault-about-t.webp";
import f179 from "../assets/work/code/game-vault/game-vault-about-f.webp";
import t180 from "../assets/work/code/game-vault/game-vault-focus-t.webp";
import f180 from "../assets/work/code/game-vault/game-vault-focus-f.webp";
import t181 from "../assets/work/code/game-vault/game-vault-library-t.webp";
import f181 from "../assets/work/code/game-vault/game-vault-library-f.webp";
import t182 from "../assets/work/code/game-vault/game-vault-tier-t.webp";
import f182 from "../assets/work/code/game-vault/game-vault-tier-f.webp";
import t183 from "../assets/work/code/game-vault/game-vault-top-t.webp";
import f183 from "../assets/work/code/game-vault/game-vault-top-f.webp";
import t184 from "../assets/work/code/hashmap-hashset/01-hashmap-list-t.webp";
import f184 from "../assets/work/code/hashmap-hashset/01-hashmap-list-f.webp";
import t185 from "../assets/work/code/hashmap-hashset/02-hashmap-query-t.webp";
import f185 from "../assets/work/code/hashmap-hashset/02-hashmap-query-f.webp";
import t186 from "../assets/work/code/hashmap-hashset/03-hashset-list-t.webp";
import f186 from "../assets/work/code/hashmap-hashset/03-hashset-list-f.webp";
import t187 from "../assets/work/code/hashmap-hashset/04-hashset-query-t.webp";
import f187 from "../assets/work/code/hashmap-hashset/04-hashset-query-f.webp";
import t188 from "../assets/work/code/knights-travails/knight-travails-base-t.webp";
import f188 from "../assets/work/code/knights-travails/knight-travails-base-f.webp";
import t189 from "../assets/work/code/knights-travails/knight-travails-random-t.webp";
import f189 from "../assets/work/code/knights-travails/knight-travails-random-f.webp";
import t190 from "../assets/work/code/linked-list/linked-list-list-t.webp";
import f190 from "../assets/work/code/linked-list/linked-list-list-f.webp";
import t191 from "../assets/work/code/linked-list/linked-list-list-details-t.webp";
import f191 from "../assets/work/code/linked-list/linked-list-list-details-f.webp";
import t192 from "../assets/work/code/weather-report/weather-report-cloudy-t.webp";
import f192 from "../assets/work/code/weather-report/weather-report-cloudy-f.webp";
import t193 from "../assets/work/code/weather-report/weather-report-genova-t.webp";
import f193 from "../assets/work/code/weather-report/weather-report-genova-f.webp";
import t194 from "../assets/work/code/weather-report/weather-report-night-t.webp";
import f194 from "../assets/work/code/weather-report/weather-report-night-f.webp";
import t195 from "../assets/work/code/weather-report/weather-report-rain-t.webp";
import f195 from "../assets/work/code/weather-report/weather-report-rain-f.webp";

export const images = {
  "art/msr/blackhat": [
    { id: "blackhat", name: "Black Hat", thumb: t0, full: f0, tw: 720, w: 2000, h: 1888 },
    { id: "blackhat-details", name: "Blackhat Details", thumb: t1, full: f1, tw: 720, w: 2000, h: 1125 },
    { id: "blackhat-face", name: "Blackhat Face", thumb: t2, full: f2, tw: 536, w: 1331, h: 1788 },
  ],
  "art/msr/greyhat": [
    { id: "greyhat", name: "Grey Hat", thumb: t3, full: f3, tw: 720, w: 2000, h: 1888 },
    { id: "greyhat-details", name: "Greyhat Details", thumb: t4, full: f4, tw: 720, w: 2000, h: 1125 },
    { id: "greyhat-face", name: "Greyhat Face", thumb: t5, full: f5, tw: 598, w: 1534, h: 1848 },
  ],
  "art/msr/presentation": [
    { id: "msr-the-hat-hackers-rw-1", name: "Board 01", thumb: t6, full: f6, tw: 720, w: 2000, h: 1229 },
    { id: "msr-the-hat-hackers-rw-2", name: "Board 02", thumb: t7, full: f7, tw: 720, w: 2000, h: 1229 },
    { id: "msr-the-hat-hackers-rw-3", name: "Board 03", thumb: t8, full: f8, tw: 720, w: 2000, h: 1229 },
    { id: "msr-the-hat-hackers-rw-4", name: "Board 04", thumb: t9, full: f9, tw: 720, w: 2000, h: 1229 },
    { id: "msr-the-hat-hackers-rw-5", name: "Board 05", thumb: t10, full: f10, tw: 720, w: 2000, h: 1229 },
    { id: "msr-the-hat-hackers-rw-6", name: "Board 06", thumb: t11, full: f11, tw: 720, w: 2000, h: 1229 },
    { id: "msr-the-hat-hackers-rw-7", name: "Board 07", thumb: t12, full: f12, tw: 720, w: 2000, h: 1229 },
    { id: "msr-the-hat-hackers-rw-8", name: "Board 08", thumb: t13, full: f13, tw: 720, w: 2000, h: 1229 },
    { id: "msr-the-hat-hackers-rw-9", name: "Board 09", thumb: t14, full: f14, tw: 720, w: 2000, h: 1229 },
    { id: "msr-the-hat-hackers-rw-10", name: "Board 10", thumb: t15, full: f15, tw: 720, w: 2000, h: 1229 },
    { id: "msr-the-hat-hackers-rw-11", name: "Board 11", thumb: t16, full: f16, tw: 720, w: 2000, h: 1229 },
    { id: "msr-the-hat-hackers-rw-12", name: "Board 12", thumb: t17, full: f17, tw: 720, w: 2000, h: 1229 },
  ],
  "art/msr/whitehat": [
    { id: "whitehat", name: "White Hat", thumb: t18, full: f18, tw: 536, w: 1489, h: 2000 },
    { id: "whitehat-details", name: "Whitehat Details", thumb: t19, full: f19, tw: 720, w: 2000, h: 1125 },
    { id: "whitehat-face", name: "Whitehat Face", thumb: t20, full: f20, tw: 497, w: 1308, h: 1896 },
  ],
  "art/nemixar/characters": [
    { id: "tnbp-ninjasfin", name: "Ninjasfin", thumb: t21, full: f21, tw: 720, w: 2000, h: 1125 },
    { id: "tnsp-cassie", name: "Cassie", thumb: t22, full: f22, tw: 720, w: 2000, h: 1125 },
    { id: "tnsp-cpt-bonechuckle", name: "Captain Bonechuckle", thumb: t23, full: f23, tw: 720, w: 2000, h: 1125 },
    { id: "tnsp-cunny-molly", name: "Cunny Molly", thumb: t24, full: f24, tw: 720, w: 2000, h: 1125 },
    { id: "tnsp-flashey", name: "Flashey", thumb: t25, full: f25, tw: 720, w: 2000, h: 1125 },
    { id: "tnsp-iappo", name: "Iappo", thumb: t26, full: f26, tw: 720, w: 2000, h: 1125 },
    { id: "tnsp-nyxia", name: "Nyxia", thumb: t27, full: f27, tw: 720, w: 2000, h: 1125 },
    { id: "tnsp-ramon", name: "Ramon", thumb: t28, full: f28, tw: 720, w: 2000, h: 1125 },
  ],
  "art/nemixar/land-invasion": [
    { id: "liguide-0", name: "Cover", thumb: t29, full: f29, tw: 720, w: 2000, h: 1000 },
    { id: "liguide-1-2", name: "Pages 1-2", thumb: t30, full: f30, tw: 720, w: 2000, h: 1000 },
    { id: "liguide-3-4", name: "Pages 3-4", thumb: t31, full: f31, tw: 720, w: 2000, h: 1000 },
    { id: "liguide-5-6", name: "Pages 5-6", thumb: t32, full: f32, tw: 720, w: 2000, h: 1000 },
    { id: "liguide-7-8", name: "Pages 7-8", thumb: t33, full: f33, tw: 720, w: 2000, h: 1000 },
  ],
  "art/personal-drawings/arcaster": [
    { id: "arcaster", name: "Arcaster", thumb: t34, full: f34, tw: 718, w: 1994, h: 2000 },
    { id: "arcaster-details", name: "Arcaster Details", thumb: t35, full: f35, tw: 617, w: 1713, h: 2000 },
    { id: "arcaster-inspo", name: "Arcaster Inspiration", thumb: t36, full: f36, tw: 617, w: 1713, h: 2000 },
  ],
  "art/personal-drawings/creature-study": [
    { id: "arctic-predator", name: "Arctic Predator", thumb: t37, full: f37, tw: 720, w: 2000, h: 1026 },
    { id: "arctic-prey", name: "Arctic Prey", thumb: t38, full: f38, tw: 720, w: 2000, h: 1026 },
    { id: "chimeras", name: "Chimeras", thumb: t39, full: f39, tw: 720, w: 2000, h: 1026 },
    { id: "choice", name: "Choice", thumb: t40, full: f40, tw: 720, w: 2000, h: 1026 },
  ],
  "art/personal-drawings/genista": [
    { id: "genista", name: "Genista", thumb: t41, full: f41, tw: 586, w: 1628, h: 2000 },
    { id: "genista-details", name: "Genista Details", thumb: t42, full: f42, tw: 720, w: 2000, h: 2000 },
    { id: "genista-palettes", name: "Genista Palettes", thumb: t43, full: f43, tw: 720, w: 2000, h: 1633 },
    { id: "genista-sketches", name: "Genista Sketches", thumb: t44, full: f44, tw: 720, w: 2000, h: 1633 },
  ],
  "art/personal-drawings/kurowo": [
    { id: "kurowo", name: "Kurowo", thumb: t45, full: f45, tw: 560, w: 1556, h: 2000 },
    { id: "kurowo-inspo", name: "Kurowo Inspiration", thumb: t46, full: f46, tw: 720, w: 2000, h: 1024 },
    { id: "kurowo-palettes", name: "Kurowo Palettes", thumb: t47, full: f47, tw: 720, w: 2000, h: 1024 },
    { id: "kurowo-render", name: "Kurowo Render", thumb: t48, full: f48, tw: 720, w: 2000, h: 1024 },
    { id: "kurowo-sketches", name: "Kurowo Sketches", thumb: t49, full: f49, tw: 720, w: 2000, h: 1024 },
    { id: "kurowohouse", name: "Kurowo House", thumb: t50, full: f50, tw: 720, w: 2000, h: 1556 },
    { id: "kurowohouse-inspo", name: "Kurowo House Inspiration", thumb: t51, full: f51, tw: 720, w: 2000, h: 1024 },
    { id: "kurowohouse-palettes", name: "Kurowo House Palettes", thumb: t52, full: f52, tw: 720, w: 2000, h: 1024 },
    { id: "kurowohouse-render", name: "Kurowo House Render", thumb: t53, full: f53, tw: 720, w: 2000, h: 1024 },
    { id: "kurowohouse-sketches", name: "Kurowo House Sketches", thumb: t54, full: f54, tw: 720, w: 2000, h: 1024 },
  ],
  "art/personal-drawings/material-study": [
    { id: "materials1", name: "Materials 1", thumb: t55, full: f55, tw: 720, w: 2000, h: 2000 },
    { id: "materials2", name: "Materials 2", thumb: t56, full: f56, tw: 720, w: 2000, h: 2000 },
    { id: "potion", name: "Potion", thumb: t57, full: f57, tw: 560, w: 1556, h: 2000 },
  ],
  "art/personal-drawings/non": [
    { id: "non", name: "Non", thumb: t58, full: f58, tw: 560, w: 1556, h: 2000 },
    { id: "non-inspo", name: "Non Inspiration", thumb: t59, full: f59, tw: 720, w: 2000, h: 1024 },
    { id: "non-palettes", name: "Non Palettes", thumb: t60, full: f60, tw: 720, w: 2000, h: 1024 },
    { id: "non-render", name: "Non Render", thumb: t61, full: f61, tw: 720, w: 2000, h: 1024 },
    { id: "non-sketches", name: "Non Sketches", thumb: t62, full: f62, tw: 720, w: 2000, h: 1024 },
    { id: "nonroom", name: "Non Room", thumb: t63, full: f63, tw: 720, w: 2000, h: 1556 },
    { id: "nonroom-cellshading", name: "Non Room Cell Shading", thumb: t64, full: f64, tw: 720, w: 2000, h: 1024 },
    { id: "nonroom-inspo", name: "Non Room Inspiration", thumb: t65, full: f65, tw: 720, w: 2000, h: 1024 },
    { id: "nonroom-palettes", name: "Non Room Palettes", thumb: t66, full: f66, tw: 720, w: 2000, h: 1024 },
    { id: "nonroom-sketch", name: "Non Room Sketch", thumb: t67, full: f67, tw: 720, w: 2000, h: 1024 },
  ],
  "art/personal-drawings/nora": [
    { id: "nora", name: "Nora", thumb: t68, full: f68, tw: 720, w: 2000, h: 1999 },
    { id: "nora-details", name: "Nora Details", thumb: t69, full: f69, tw: 720, w: 2000, h: 1711 },
    { id: "nora-inspo", name: "Nora Inspiration", thumb: t70, full: f70, tw: 720, w: 2000, h: 1298 },
    { id: "nora-palettes", name: "Nora Palettes", thumb: t71, full: f71, tw: 720, w: 2000, h: 1298 },
    { id: "nora-sketch", name: "Nora Sketch", thumb: t72, full: f72, tw: 720, w: 2000, h: 1298 },
  ],
  "art/personal-drawings/rendering-study": [
    { id: "portrait-cartoon", name: "Portrait Cartoon", thumb: t73, full: f73, tw: 720, w: 1000, h: 774 },
    { id: "portrait-from-photo", name: "Portrait From Photo", thumb: t74, full: f74, tw: 720, w: 2000, h: 1255 },
    { id: "render-orc-1", name: "Render Orc 1", thumb: t75, full: f75, tw: 720, w: 2000, h: 1869 },
    { id: "render-orc-2", name: "Render Orc 2", thumb: t76, full: f76, tw: 720, w: 2000, h: 2000 },
    { id: "render-orc-3", name: "Render Orc 3", thumb: t77, full: f77, tw: 720, w: 2000, h: 2000 },
  ],
  "art/personal-drawings/shading-study": [
    { id: "face-shading", name: "Face Shading", thumb: t78, full: f78, tw: 720, w: 2000, h: 1434 },
    { id: "lights1", name: "Lights 1", thumb: t79, full: f79, tw: 720, w: 1000, h: 804 },
    { id: "lights2", name: "Lights 2", thumb: t80, full: f80, tw: 720, w: 2000, h: 1608 },
    { id: "lights3", name: "Lights 3", thumb: t81, full: f81, tw: 720, w: 1000, h: 804 },
    { id: "shapes1", name: "Shapes 1", thumb: t82, full: f82, tw: 639, w: 888, h: 1000 },
    { id: "shapes2", name: "Shapes 2", thumb: t83, full: f83, tw: 646, w: 897, h: 1000 },
    { id: "shapes3", name: "Shapes 3", thumb: t84, full: f84, tw: 638, w: 886, h: 1000 },
    { id: "shapes4", name: "Shapes 4", thumb: t85, full: f85, tw: 641, w: 890, h: 1000 },
    { id: "shapes5", name: "Shapes 5", thumb: t86, full: f86, tw: 638, w: 960, h: 1083 },
  ],
  "art/ymdir/designs": [
    { id: "boar", name: "Boar", thumb: t87, full: f87, tw: 720, w: 2000, h: 1126 },
    { id: "kra-khom", name: "Kra’khom", thumb: t88, full: f88, tw: 720, w: 2000, h: 1499 },
    { id: "kra-khom-ta", name: "Kra’khom turnaround", thumb: t89, full: f89, tw: 720, w: 2000, h: 735 },
    { id: "props", name: "Props", thumb: t90, full: f90, tw: 720, w: 2000, h: 447 },
    { id: "wolf", name: "Wolf", thumb: t91, full: f91, tw: 720, w: 2000, h: 1126 },
  ],
  "art/ymdir/dice": [
    { id: "copy-of-s-d-analyze", name: "Analyze", thumb: t92, full: f92, tw: 720, w: 900, h: 900 },
    { id: "copy-of-s-d-bidingtime", name: "Biding Time", thumb: t93, full: f93, tw: 720, w: 900, h: 900 },
    { id: "copy-of-s-d-changeofplans", name: "Change Of Plans", thumb: t94, full: f94, tw: 720, w: 900, h: 900 },
    { id: "copy-of-s-d-channel", name: "Channel", thumb: t95, full: f95, tw: 720, w: 900, h: 900 },
    { id: "copy-of-s-d-climax", name: "Climax", thumb: t96, full: f96, tw: 720, w: 900, h: 900 },
    { id: "copy-of-s-d-criticalstrike", name: "Critical Strike", thumb: t97, full: f97, tw: 720, w: 900, h: 900 },
    { id: "copy-of-s-d-defensivestance", name: "Defensive Stance", thumb: t98, full: f98, tw: 720, w: 900, h: 900 },
    { id: "copy-of-s-d-freezeburn", name: "Freezeburn", thumb: t99, full: f99, tw: 720, w: 900, h: 900 },
    { id: "copy-of-s-d-hunterssight", name: "Hunters Sight", thumb: t100, full: f100, tw: 720, w: 900, h: 900 },
    { id: "copy-of-s-d-hunterssight-v2", name: "Hunters Sight v2", thumb: t101, full: f101, tw: 720, w: 900, h: 900 },
    { id: "copy-of-s-d-icebarrier", name: "Ice Barrier", thumb: t102, full: f102, tw: 720, w: 900, h: 900 },
    { id: "copy-of-s-d-lacerate", name: "Lacerate", thumb: t103, full: f103, tw: 720, w: 900, h: 900 },
    { id: "copy-of-s-d-poke", name: "Poke", thumb: t104, full: f104, tw: 720, w: 2000, h: 682 },
    { id: "copy-of-s-d-pummel", name: "Pummel", thumb: t105, full: f105, tw: 720, w: 2000, h: 682 },
    { id: "copy-of-s-d-recklessstrike", name: "Reckless Strike", thumb: t106, full: f106, tw: 720, w: 900, h: 900 },
    { id: "copy-of-s-d-redirection", name: "Redirection", thumb: t107, full: f107, tw: 720, w: 900, h: 900 },
    { id: "copy-of-s-d-searingcut", name: "Searing Cut", thumb: t108, full: f108, tw: 720, w: 900, h: 900 },
    { id: "copy-of-s-d-shield", name: "Shield", thumb: t109, full: f109, tw: 720, w: 900, h: 900 },
    { id: "copy-of-s-d-slice", name: "Slice", thumb: t110, full: f110, tw: 720, w: 2000, h: 680 },
    { id: "copy-of-s-d-spectralblades", name: "Spectral Blades", thumb: t111, full: f111, tw: 720, w: 900, h: 900 },
    { id: "copy-of-s-d-spikes", name: "Spikes", thumb: t112, full: f112, tw: 720, w: 900, h: 900 },
    { id: "copy-of-s-d-wisenedstrike", name: "Wisened Strike", thumb: t113, full: f113, tw: 720, w: 900, h: 900 },
    { id: "copy-of-s-d-wrath", name: "Wrath", thumb: t114, full: f114, tw: 720, w: 900, h: 900 },
  ],
  "art/ymdir/map-and-ui": [
    { id: "map-ui", name: "Map UI", thumb: t115, full: f115, tw: 720, w: 1920, h: 1080 },
    { id: "ymdir-map", name: "Ymdir map", thumb: t116, full: f116, tw: 720, w: 1999, h: 2000 },
  ],
  "art/ymdir/old-designs": [
    { id: "bat", name: "Bat", thumb: t117, full: f117, tw: 720, w: 2000, h: 1481 },
    { id: "bat-turnaround", name: "Bat turnaround", thumb: t118, full: f118, tw: 720, w: 2000, h: 609 },
    { id: "beasts1", name: "Beasts 1", thumb: t119, full: f119, tw: 720, w: 2000, h: 2000 },
    { id: "beasts2", name: "Beasts 2", thumb: t120, full: f120, tw: 720, w: 2000, h: 2000 },
    { id: "beasts3", name: "Beasts 3", thumb: t121, full: f121, tw: 720, w: 2000, h: 2000 },
    { id: "beasts4", name: "Beasts 4", thumb: t122, full: f122, tw: 720, w: 2000, h: 2000 },
    { id: "beasts5", name: "Beasts 5", thumb: t123, full: f123, tw: 720, w: 2000, h: 2000 },
    { id: "beasts-ta", name: "Beasts turnaround", thumb: t124, full: f124, tw: 720, w: 2000, h: 2000 },
    { id: "big-bandit", name: "Big bandit", thumb: t125, full: f125, tw: 720, w: 2000, h: 1481 },
    { id: "blob", name: "Blob", thumb: t126, full: f126, tw: 720, w: 2000, h: 1481 },
    { id: "blob-turn", name: "Blob turnaround", thumb: t127, full: f127, tw: 720, w: 2000, h: 609 },
    { id: "golemboss", name: "Golem Boss", thumb: t128, full: f128, tw: 720, w: 2000, h: 1400 },
    { id: "great-wolf-new", name: "Great wolf New", thumb: t129, full: f129, tw: 720, w: 2000, h: 1005 },
    { id: "kah-krom", name: "Kah Krom", thumb: t130, full: f130, tw: 720, w: 2000, h: 1400 },
    { id: "logo", name: "Logo", thumb: t131, full: f131, tw: 720, w: 2000, h: 1125 },
    { id: "lokyr", name: "Lokyr", thumb: t132, full: f132, tw: 720, w: 2000, h: 1400 },
    { id: "mad-burger-logo", name: "Mad Burger Logo", thumb: t133, full: f133, tw: 579, w: 1610, h: 2000 },
    { id: "riam", name: "Riam", thumb: t134, full: f134, tw: 720, w: 2000, h: 1400 },
    { id: "riam0", name: "Riam 0", thumb: t135, full: f135, tw: 720, w: 2000, h: 1400 },
    { id: "riam2", name: "Riam 2", thumb: t136, full: f136, tw: 720, w: 2000, h: 1192 },
    { id: "riam3", name: "Riam 3", thumb: t137, full: f137, tw: 720, w: 2000, h: 1362 },
    { id: "riam4", name: "Riam 4", thumb: t138, full: f138, tw: 720, w: 2000, h: 1400 },
    { id: "riam-2", name: "Riam", thumb: t139, full: f139, tw: 720, w: 2000, h: 1481 },
    { id: "riamthumbnail", name: "Riam Thumbnail", thumb: t140, full: f140, tw: 720, w: 2000, h: 1104 },
    { id: "rogue", name: "Rogue", thumb: t141, full: f141, tw: 720, w: 2000, h: 1126 },
    { id: "rogue-2", name: "Rogue", thumb: t142, full: f142, tw: 720, w: 2000, h: 2000 },
    { id: "rogueboss", name: "Rogue Boss", thumb: t143, full: f143, tw: 720, w: 2000, h: 1126 },
    { id: "sha-rah-harper", name: "Sha Rah Harper", thumb: t144, full: f144, tw: 720, w: 2000, h: 1400 },
  ],
  "art/ymdir/old-dice": [
    { id: "copy-of-eternal-dice-nobg", name: "Eternal Dice", thumb: t145, full: f145, tw: 370, w: 370, h: 364 },
    { id: "copy-of-heavy-dice-nobg", name: "Heavy Dice", thumb: t146, full: f146, tw: 411, w: 411, h: 392 },
    { id: "copy-of-negative-dice-nobg", name: "Negative Dice", thumb: t147, full: f147, tw: 380, w: 380, h: 360 },
    { id: "copy-of-normal-dice-nobg", name: "Normal Dice", thumb: t148, full: f148, tw: 382, w: 382, h: 359 },
    { id: "copy-of-reckless-dice-nobg", name: "Reckless Dice", thumb: t149, full: f149, tw: 512, w: 512, h: 460 },
    { id: "copy-of-tombstone-dice-nobg", name: "Tombstone Dice", thumb: t150, full: f150, tw: 379, w: 379, h: 456 },
  ],
  "art/ymdir/old-ui": [
    { id: "old-icons", name: "Old Icons", thumb: t151, full: f151, tw: 720, w: 2000, h: 1139 },
    { id: "vfx-att-debuff", name: "VFX att debuff", thumb: t152, full: f152, tw: 720, w: 2000, h: 1280 },
    { id: "vfx-berserk", name: "VFX berserk", thumb: t153, full: f153, tw: 720, w: 2000, h: 1280 },
    { id: "vfx-berserk-and-frostbite-1", name: "VFX berserk and frostbite 1", thumb: t154, full: f154, tw: 720, w: 2000, h: 1280 },
    { id: "vfx-buff", name: "VFX buff", thumb: t155, full: f155, tw: 720, w: 2000, h: 1280 },
    { id: "vfx-def", name: "VFX def", thumb: t156, full: f156, tw: 720, w: 2000, h: 1280 },
    { id: "vfx-def-debuff", name: "VFX def debuff", thumb: t157, full: f157, tw: 720, w: 2000, h: 1280 },
    { id: "vfx-frostbite", name: "VFX frostbite", thumb: t158, full: f158, tw: 720, w: 2000, h: 1280 },
    { id: "vfx-heal", name: "VFX heal", thumb: t159, full: f159, tw: 720, w: 2000, h: 1280 },
  ],
  "art/ymdir/vfx": [
    { id: "banditvfx", name: "Bandit VFX", thumb: t160, full: f160, tw: 504, w: 1400, h: 2000 },
    { id: "big-bandit-vfx", name: "Big Bandit VFX", thumb: t161, full: f161, tw: 720, w: 2000, h: 1336 },
    { id: "boar-vfx", name: "Boar VFX", thumb: t162, full: f162, tw: 504, w: 1400, h: 2000 },
    { id: "elemental-vfx", name: "Elemental VFX", thumb: t163, full: f163, tw: 434, w: 1205, h: 2000 },
    { id: "king-boar-vfx", name: "King Boar VFX", thumb: t164, full: f164, tw: 302, w: 838, h: 2000 },
    { id: "priest-vfx", name: "Priest VFX", thumb: t165, full: f165, tw: 719, w: 1997, h: 2000 },
    { id: "small-golem-vfx", name: "Small Golem VFX", thumb: t166, full: f166, tw: 604, w: 1678, h: 2000 },
    { id: "wolf-vfx", name: "Wolf VFX", thumb: t167, full: f167, tw: 503, w: 1398, h: 2000 },
    { id: "wyvern-memory-vfx", name: "Wyvern-Memory VFX", thumb: t168, full: f168, tw: 720, w: 2000, h: 1668 },
  ],
  "code/b-d-a": [
    { id: "bda-01-schermata-principale", name: "Bda-01-schermata-principale", thumb: t169, full: f169, tw: 720, w: 2000, h: 1371 },
    { id: "bda-02-focus-task", name: "Bda-02-focus-task", thumb: t170, full: f170, tw: 720, w: 2000, h: 1371 },
    { id: "bda-03-calendario", name: "Bda-03-calendario", thumb: t171, full: f171, tw: 720, w: 2000, h: 1371 },
  ],
  "code/battleship-exe": [
    { id: "battleship-01-start", name: "Battleship-01-start", thumb: t172, full: f172, tw: 720, w: 2000, h: 1250 },
    { id: "battleship-02-placement", name: "Battleship-02-placement", thumb: t173, full: f173, tw: 720, w: 2000, h: 1250 },
    { id: "battleship-03-gameplay", name: "Battleship-03-gameplay", thumb: t174, full: f174, tw: 720, w: 2000, h: 1250 },
    { id: "battleship-04-win", name: "Battleship-04-win", thumb: t175, full: f175, tw: 720, w: 2000, h: 1250 },
  ],
  "code/binary-search-trees": [
    { id: "bst-01-initial", name: "Bst-01-initial", thumb: t176, full: f176, tw: 720, w: 2000, h: 1728 },
    { id: "bst-02-insert-many", name: "Bst-02-insert-many", thumb: t177, full: f177, tw: 720, w: 2000, h: 1728 },
    { id: "bst-03-rebalance", name: "Bst-03-rebalance", thumb: t178, full: f178, tw: 720, w: 2000, h: 1728 },
  ],
  "code/game-vault": [
    { id: "game-vault-about", name: "Game-Vault About", thumb: t179, full: f179, tw: 720, w: 2000, h: 1229 },
    { id: "game-vault-focus", name: "Game-Vault Focus", thumb: t180, full: f180, tw: 720, w: 2000, h: 1229 },
    { id: "game-vault-library", name: "Game-Vault Library", thumb: t181, full: f181, tw: 720, w: 2000, h: 1229 },
    { id: "game-vault-tier", name: "Game-Vault Tier", thumb: t182, full: f182, tw: 720, w: 2000, h: 1229 },
    { id: "game-vault-top", name: "Game-Vault Top", thumb: t183, full: f183, tw: 720, w: 2000, h: 1229 },
  ],
  "code/hashmap-hashset": [
    { id: "01-hashmap-list", name: "01-hashmap-list", thumb: t184, full: f184, tw: 720, w: 2000, h: 1286 },
    { id: "02-hashmap-query", name: "02-hashmap-query", thumb: t185, full: f185, tw: 720, w: 2000, h: 1286 },
    { id: "03-hashset-list", name: "03-hashset-list", thumb: t186, full: f186, tw: 720, w: 2000, h: 1286 },
    { id: "04-hashset-query", name: "04-hashset-query", thumb: t187, full: f187, tw: 720, w: 2000, h: 1286 },
  ],
  "code/knights-travails": [
    { id: "knight-travails-base", name: "Knight-Travails Base", thumb: t188, full: f188, tw: 720, w: 2000, h: 1229 },
    { id: "knight-travails-random", name: "Knight-Travails Random", thumb: t189, full: f189, tw: 720, w: 2000, h: 1229 },
  ],
  "code/linked-list": [
    { id: "linked-list-list", name: "Linked-List List", thumb: t190, full: f190, tw: 720, w: 2000, h: 1229 },
    { id: "linked-list-list-details", name: "Linked-List List Details", thumb: t191, full: f191, tw: 720, w: 2000, h: 1229 },
  ],
  "code/weather-report": [
    { id: "weather-report-cloudy", name: "Weather-Report Cloudy", thumb: t192, full: f192, tw: 720, w: 2000, h: 1229 },
    { id: "weather-report-genova", name: "Weather-Report Genova", thumb: t193, full: f193, tw: 720, w: 2000, h: 1229 },
    { id: "weather-report-night", name: "Weather-Report Night", thumb: t194, full: f194, tw: 720, w: 2000, h: 1229 },
    { id: "weather-report-rain", name: "Weather-Report Rain", thumb: t195, full: f195, tw: 720, w: 2000, h: 1229 },
  ],
};
