import { images } from "./images.js";

/* Turns a Drive folder key ("art/msr/greyhat") into the entries a collage
   renders. images.js is generated by scripts/build-images.py.

   An entry without `src` renders as a placeholder; `ratio` (wide | tall |
   square | banner) or `ar` gives its proportions, `size` (wide | tall | big)
   how much room it takes in a collage. */

export const LOREM_CAPTION =
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio, praesent libero sed cursus ante dapibus diam.";

const shot = (label, ratio = "wide", size) => ({
  label,
  ratio,
  size,
  caption: LOREM_CAPTION,
});

// A quick run of placeholder shots with a varied rhythm, so collages look like
// collages before the real art arrives.
const RHYTHM = [
  ["wide", "wide"],
  ["tall"],
  ["square"],
  ["tall", "tall"],
  ["wide"],
  ["square"],
  ["wide", "big"],
  ["tall"],
  ["square"],
  ["wide"],
];
export const shots = (prefix, n) =>
  Array.from({ length: n }, (_, i) => {
    const [ratio, size] = RHYTHM[i % RHYTHM.length];
    return shot(`${prefix} ${String(i + 1).padStart(2, "0")}`, ratio, size);
  });

/* The real pieces for a Drive folder (see scripts/build-images.py). How much
   room a piece takes in the collage follows its own proportions; the first one
   leads, big. Falls back to placeholders for a folder that has no images yet. */
export const pics = (key, fallback = 6) => {
  const list = images[key];
  if (!list) return shots(key.split("/").pop(), fallback);
  return list.map((img, i) => {
    const ar = img.w / img.h;
    // Strips (dice sheets, panoramas) would be cut to a sliver by cropping, so
    // they are shown whole and never lead as the big piece.
    const strip = ar >= 2.5;
    let size;
    if (strip) size = "wide";
    else if (i === 0) size = "big";
    else if (ar >= 1.5) size = "wide";
    else if (ar <= 0.8) size = "tall";
    return {
      fit: strip,
      label: img.name,
      src: img.thumb,
      full: img.full,
      ar,
      size,
      caption: LOREM_CAPTION,
    };
  });
};
