import { images } from "./images.js";

/* Turns a Drive folder key ("art/msr/greyhat") into the entries a collage
   renders. images.js is generated by scripts/build-images.py.

   An entry without `src` renders as a placeholder; `ratio` (wide | tall |
   square | banner) or `ar` gives its proportions. */

// Pieces have no captions of their own yet; the lightbox hides "info" when
// there is nothing to show.
export const LOREM_CAPTION = "";

const shot = (label, ratio = "wide") => ({
  label,
  ratio,
  caption: LOREM_CAPTION,
});

// A quick run of placeholder shots with a varied rhythm, so collages look like
// collages before the real art arrives.
const RHYTHM = ["wide", "tall", "square", "tall", "wide", "square", "wide", "tall", "square", "wide"];
export const shots = (prefix, n) =>
  Array.from({ length: n }, (_, i) =>
    shot(`${prefix} ${String(i + 1).padStart(2, "0")}`, RHYTHM[i % RHYTHM.length]),
  );

/* The real pieces for a Drive folder (see scripts/build-images.py). Each keeps
   its own proportions in the collage. Falls back to placeholders for a folder
   that has no images yet. */
export const pics = (key, fallback = 6) => {
  const list = images[key];
  if (!list) return shots(key.split("/").pop(), fallback);
  return list.map((img) => ({
    label: img.name,
    src: img.thumb,
    full: img.full,
    ar: img.w / img.h,
    w: img.w,
    caption: LOREM_CAPTION,
  }));
};
