import { images } from "./images.js";
import { t } from "../i18n.js";

/* The pieces for a Drive folder key ("art/msr/greyhat"), as a gallery shows
   them. images.js is generated by scripts/build-images.py, which already
   turns the file names into readable ones. A folder with nothing exported
   yet has no pieces, and its gallery is simply left out. */

// Each step of the process says what it was for, so a sheet of sketches reads
// as a stage rather than a leftover. Matched on the end of the file's slug.
const STAGES = [
  [["-inspo"], "The inspiration board: references for shape, costume and mood, gathered before the first line."],
  [["-sketch", "-sketches"], "Sketches: silhouettes and poses tried side by side, to find the shape before any detail."],
  [["-palettes"], "Palette explorations: the same design in several colour schemes, before one is chosen."],
  [["-cell-shading"], "A cell-shaded pass, testing a flatter, more graphic finish."],
  [["-details"], "Details: close-ups where the costume, props and materials get worked out."],
  [["-face"], "The face sheet: expressions and features, to pin down who the character is."],
  [["-ta", "-turn", "-turnaround"], "Turnaround: the design from every side, as reference for modelling and animation."],
  [["-render"], "The render: the chosen sketch and palette taken to a finished image."],
];

const captionFor = (id) => STAGES.find(([ends]) => ends.some((end) => id.endsWith(end)))?.[1] ?? "";

const cache = new Map();

export const pics = (key) => {
  if (!cache.has(key)) {
    cache.set(
      key,
      (images[key] ?? []).map((img) => ({
        id: img.id,
        label: t(img.name),
        src: img.thumb,
        full: img.full,
        tw: img.tw,
        w: img.w,
        ar: img.w / img.h,
        caption: t(captionFor(img.id)),
      })),
    );
  }
  return cache.get(key);
};
