"""Turns the Drive export in raw/ into web images plus the module that lists them.

    python3 scripts/build-images.py

raw/ mirrors the Drive folder (Art/<Series>/<Project>/..., Code/<Project>/...)
and stays out of git. For every image this writes two WebP files under
src/assets/work/ (a thumbnail for collages and a full size for the lightbox)
and regenerates src/content/images.js, which imports them so webpack hashes and
ships them. Anything deeper than <Series>/<Project> (Presentation/Slides,
Old Designs/Riam) is folded into its project. Re-running only encodes what
changed and removes outputs whose source is gone.
"""

import re
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
RAW = ROOT / "raw"
OUT = ROOT / "src" / "assets" / "work"
MODULE = ROOT / "src" / "content" / "images.js"

THUMB = 720  # longest side, enough for a 2x2 collage cell on a retina screen
FULL = 2000
QUALITY = 80
EXTS = {".png", ".jpg", ".jpeg", ".webp"}


def slug(text):
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def natural(text):
    return [int(t) if t.isdigit() else t.lower() for t in re.split(r"(\d+)", text)]


def pretty(stem):
    """'Copy of S_D_BidingTime' -> 'Biding Time'."""
    stem = re.sub(r"^Copy of ", "", stem)
    stem = re.sub(r"^S_D_", "", stem)
    stem = re.sub(r"(?<=[a-z])(?=[A-Z])", " ", stem)
    return re.sub(r"[_\s]+", " ", stem).strip()


def key_for(path):
    """Art/MSR/Presentation/Slides/x.png -> ('art/msr/presentation')."""
    parts = path.relative_to(RAW).parts
    depth = 3 if parts[0] == "Art" else 2
    return "/".join(slug(p) for p in parts[:depth])


def encode(src, dest, size):
    if dest.exists() and dest.stat().st_mtime >= src.stat().st_mtime:
        return
    with Image.open(src) as im:
        im = im.convert("RGBA" if im.mode in ("RGBA", "LA", "P") else "RGB")
        im.thumbnail((size, size), Image.LANCZOS)
        dest.parent.mkdir(parents=True, exist_ok=True)
        im.save(dest, "WEBP", quality=QUALITY, method=6)


def main():
    groups = {}
    for f in sorted(RAW.rglob("*")):
        if f.is_file() and f.suffix.lower() in EXTS:
            groups.setdefault(key_for(f), []).append(f)

    written = set()
    entries = {}
    for key, files in sorted(groups.items()):
        folder = key.rsplit("/", 1)[-1]
        # The piece named like its folder (GreyHat.png in GreyHat/) is the
        # finished one, so it leads and becomes the cover.
        files.sort(key=lambda f: (slug(f.stem) != folder, natural(f.stem)))
        entries[key] = []
        for f in files:
            name = slug(f.stem)
            thumb = OUT / key / f"{name}-t.webp"
            full = OUT / key / f"{name}-f.webp"
            encode(f, thumb, THUMB)
            encode(f, full, FULL)
            written.update((thumb, full))
            with Image.open(f) as im:
                w, h = im.size
            entries[key].append((pretty(f.stem), thumb, full, w, h))
        print(f"{len(files):3}  {key}")

    for stale in OUT.rglob("*.webp"):
        if stale not in written:
            stale.unlink()

    imports, groups_js = [], []
    n = 0
    for key, items in entries.items():
        rows = []
        for name, thumb, full, w, h in items:
            t = thumb.relative_to(MODULE.parent.parent).as_posix()
            fu = full.relative_to(MODULE.parent.parent).as_posix()
            imports.append(f'import t{n} from "../{t}";\nimport f{n} from "../{fu}";')
            safe = name.replace('"', '\\"')
            rows.append(f'    {{ name: "{safe}", thumb: t{n}, full: f{n}, w: {w}, h: {h} }},')
            n += 1
        groups_js.append(f'  "{key}": [\n' + "\n".join(rows) + "\n  ],")

    MODULE.write_text(
        "// Generated by scripts/build-images.py from raw/. Do not edit by hand.\n"
        + "\n".join(imports)
        + "\n\nexport const images = {\n"
        + "\n".join(groups_js)
        + "\n};\n"
    )
    print(f"{n} images -> {MODULE.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
