"""Turns the Drive export in raw/ into web images plus the module that lists them.

    python3 scripts/build-images.py

raw/ mirrors the Drive folder (Art/<Series>/<Project>/..., Code/<Project>/...)
and stays out of git. For every image this writes two WebP files under
src/assets/work/ (a thumbnail for strips and phones, a full size for wide
screens and the lightbox) and regenerates src/content/images.js, which imports
them so webpack hashes and ships them, with each file's slug as its id. Anything deeper than <Series>/<Project> (Presentation/Slides,
Old Designs/Riam) is folded into its project. Re-running only encodes what
changed and removes outputs whose source is gone.
"""

import re
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
RAW = ROOT / "raw"
OUT = ROOT / "src" / "assets" / "work"
MODULE = ROOT / "src" / "content" / "images.js"

THUMB = 720  # longest side: the stage on a phone, the strip everywhere
FULL = 2000
QUALITY = 80
EXTS = {".png", ".jpg", ".jpeg", ".webp"}


def slug(text):
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def natural(text):
    return [int(t) if t.isdigit() else t.lower() for t in re.split(r"(\d+)", text)]


# Drive names are working names: export prefixes, glued numbers, shorthand.
# Applied in order after camelCase and underscores are split into words.
RENAMES = [
    (r"^Copy of ", ""),
    (r"^S D ", ""),
    (r"^TN[bs]p ", ""),
    (r"^MSR- The Hat Hackers rw (\d+)$", lambda m: f"Board {int(m[1]):02}"),
    (r"^LIguide 0$", "Cover"),
    (r"^LIguide ", "Pages "),
    (r"^Cpt ", "Captain "),
    (r" NOBG$", ""),
    (r"^vfx\b", "VFX"),
    (r"\b(TA|ta|turn)$", "turnaround"),
    (r"\bInspo\b", "Inspiration"),
    (r"([a-z]{2,})(\d)", r"\1 \2"),
]


def pretty(stem):
    """'Copy of S_D_BidingTime' -> 'Biding Time', 'TNsp_Cassie' -> 'Cassie'."""
    name = re.sub(r"(?<=[a-z])(?=[A-Z])", " ", stem)
    name = re.sub(r"[_\s]+", " ", name).strip()
    for find, put in RENAMES:
        name = re.sub(find, put, name)
    return name[:1].upper() + name[1:]


def key_for(path):
    """Art/MSR/Presentation/Slides/x.png -> ('art/msr/presentation')."""
    parts = path.relative_to(RAW).parts
    depth = 3 if parts[0] == "Art" else 2
    return "/".join(slug(p) for p in parts[:depth])


def encode(src, outputs):
    """Writes each (dest, size) that is older than src, decoding src once, and
    returns the encoded (width, height) of every output."""
    if any(not d.exists() or d.stat().st_mtime < src.stat().st_mtime for d, _ in outputs):
        with Image.open(src) as im:
            im = im.convert("RGBA" if im.mode in ("RGBA", "LA", "P") else "RGB")
            for dest, size in outputs:
                out = im.copy()
                out.thumbnail((size, size), Image.LANCZOS)
                dest.parent.mkdir(parents=True, exist_ok=True)
                out.save(dest, "WEBP", quality=QUALITY, method=6)
    sizes = []
    for dest, _ in outputs:
        with Image.open(dest) as im:
            sizes.append(im.size)
    return sizes


def main():
    groups = {}
    for f in sorted(RAW.rglob("*")):
        if f.is_file() and f.suffix.lower() in EXTS:
            groups.setdefault(key_for(f), []).append(f)

    written = set()
    entries = {}
    for key, files in sorted(groups.items()):
        folder = key.rsplit("/", 1)[-1]
        # The piece named like its folder (GreyHat.png in GreyHat/) is the
        # finished one, so it leads and becomes the cover.
        files.sort(key=lambda f: (slug(f.stem) != folder, natural(f.stem)))
        entries[key] = []
        for f in files:
            name = slug(f.stem)
            thumb = OUT / key / f"{name}-t.webp"
            full = OUT / key / f"{name}-f.webp"
            (tw, _), (fw, fh) = encode(f, [(thumb, THUMB), (full, FULL)])
            written.update((thumb, full))
            entries[key].append((name, pretty(f.stem), thumb, full, tw, fw, fh))
        print(f"{len(files):3}  {key}")

    for stale in OUT.rglob("*.webp"):
        if stale not in written:
            stale.unlink()

    imports, groups_js = [], []
    n = 0
    for key, items in entries.items():
        rows = []
        for id_, name, thumb, full, tw, fw, fh in items:
            t = thumb.relative_to(MODULE.parent.parent).as_posix()
            fu = full.relative_to(MODULE.parent.parent).as_posix()
            imports.append(f'import t{n} from "../{t}";\nimport f{n} from "../{fu}";')
            safe = name.replace('"', '\\"')
            rows.append(
                f'    {{ id: "{id_}", name: "{safe}", thumb: t{n}, full: f{n}, tw: {tw}, w: {fw}, h: {fh} }},'
            )
            n += 1
        groups_js.append(f'  "{key}": [\n' + "\n".join(rows) + "\n  ],")

    MODULE.write_text(
        "// Generated by scripts/build-images.py from raw/. Do not edit by hand.\n"
        + "\n".join(imports)
        + "\n\nexport const images = {\n"
        + "\n".join(groups_js)
        + "\n};\n"
    )
    print(f"{n} images -> {MODULE.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
