import "./styles.css";
import { initAsciiField } from "./ascii/index.js";
import { initMotion } from "./motion.js";
import { renderPage } from "./render.js";
import { initLightbox } from "./lightbox.js";
import { initFolds } from "./folds.js";
import { initGalleries } from "./gallery.js";
import { initCopy } from "./copy.js";
import { initPath } from "./path.js";
import { initFade } from "./fade.js";

const field = document.querySelector(".ascii-field");
if (field) initAsciiField(field);
renderPage();
initLightbox();
initFolds();
initGalleries();
initCopy();
initPath();
initFade();
initMotion();
