import { intro as artIntro, series, order, artTimeline } from "./content/art.js";
import { intro as codeIntro, projects, toolbox, path, nextUp, GH } from "./content/code.js";
import { covers, marks } from "./content/media.js";
import { pics } from "./content/pics.js";
import { pad, esc, ext } from "./html.js";

/* Fills every Art and Code page from src/content/. The HTML files are
   generated by src/layout.js and only carry the chrome plus a hook:
     <main data-view="art">                     the Art overview
     <main data-view="series" data-id="msr">    one collection
     <main data-view="code">                    the Code overview
     <main data-view="code-project" data-id="…"> one project
   Everything here runs before motion.js, so reveals see the finished DOM. */

const count = (n, word) => `${pad(n)} ${word}`;
const paras = (list = []) => list.map((p) => `<p>${p}</p>`).join("");

const crumbs = (trail) => `
  <nav class="crumbs" aria-label="Breadcrumb">
    ${trail
      .map(([name, href]) =>
        href ? `<a href="${href}">${name}</a>` : `<span aria-current="page">${name}</span>`,
      )
      .join('<span class="crumb-sep" aria-hidden="true">/</span>')}
  </nav>`;

const brief = (rows = []) =>
  rows.length
    ? `<dl class="brief">${rows
        .map(([k, v]) => `<div class="brief-row"><dt>${k}</dt><dd>${v}</dd></div>`)
        .join("")}</dl>`
    : "";

const head = (title, meta = "") => `
  <div class="block-head"><h2>${title}</h2><span class="block-meta">${meta}</span></div>`;

/* The whole site read front to back: every section page knows what comes
   before and after it. Paths are from the site root. */
const TRAIL = [
  { href: "art.html", name: "Art" },
  ...order.map((id) => ({ href: `art/${id}.html`, name: series[id].title })),
  { href: "code.html", name: "Code" },
  ...projects.map((p) => ({ href: `code/${p.id}.html`, name: p.title })),
];

function pager(here, root) {
  const i = TRAIL.findIndex((t) => t.href === here);
  const prev = TRAIL[i - 1] ?? { href: "index.html", name: "Résumé" };
  const next = TRAIL[i + 1] ?? { href: "index.html#contact", name: "Get in touch" };
  const link = (t, dir, cls) => `
    <a class="pager-link ${cls}" href="${root}${t.href}">
      <span class="pager-dir">${dir}</span>
      <span class="pager-name">${t.name}</span></a>`;
  return `
  <nav class="pager" aria-label="Pagination">
    ${link(prev, "← Previous", "pager-prev")}
    ${link(next, "Next →", "pager-next")}
  </nav>`;
}

/* Page title block shared by both overviews and every collection. The longer
   text sits beside the title on wide screens, or under it with `stacked`. */
const zoneHead = ({ index, title, lead, body, status, stats, stacked }) => `
  <div class="zone-head${body ? (stacked ? " zone-head--stacked" : " zone-head--split") : ""}">
    <div class="zone-head-main">
      ${status ? `<span class="case-status">${status}</span>` : ""}
      <span class="zone-index" aria-hidden="true">${index}</span>
      <h1 class="zone-title">${title}</h1>
      <p class="zone-lead">${lead}</p>
    </div>
    ${body ? `<div class="zone-body">${paras(body)}</div>` : ""}
    ${
      stats
        ? `<ul class="stat-row">${stats
            .map(
              ([v, l]) =>
                `<li class="stat"><span class="stat-value">${v}</span><span class="stat-label">${l}</span></li>`,
            )
            .join("")}</ul>`
        : ""
    }
  </div>`;

/* A set of pieces as a stage and a strip. This writes the frame and the
   strip; src/gallery.js puts a piece on the stage (show()) and runs it. The
   stage keeps one shape for the whole set, picked from the pieces
   themselves, so flicking through them never makes the page jump; each piece
   sits inside it at its own proportions. */
function gallery(images, { label = "", compact = false } = {}) {
  if (!images.length) return "";
  const ars = images.map((img) => img.ar).sort((a, b) => a - b);
  const stageAr = Math.min(1.78, Math.max(0.8, ars[Math.floor(ars.length / 2)]));
  const many = images.length > 1;
  const nav = (step, name, arrow) =>
    many ? `<button type="button" class="gallery-nav" data-step="${step}" aria-label="${name}">${arrow}</button>` : "";
  const thumbs = images
    .map(
      (img) => `
      <li><button type="button" class="gallery-thumb" style="--ar: ${img.ar}" data-ratio="${img.ar}"
        data-title="${esc(img.label)}" data-caption="${esc(img.caption)}"
        data-src="${img.src}" data-full="${img.full}" data-tw="${img.tw}" data-w="${img.w}"
        aria-label="Show ${esc(img.label)}"><img src="${img.src}" alt="" loading="lazy" decoding="async" /></button></li>`,
    )
    .join("");
  return `
  <div class="gallery${compact ? " gallery--compact" : ""}" data-lightbox="${esc(label)}" data-index="0">
    <figure class="gallery-stage">
      <button type="button" class="gallery-open" style="--stage-ar: ${stageAr}"></button>
      <figcaption class="gallery-caption">
        <span class="gallery-steps">${nav(-1, "Previous", "←")}<span class="gallery-count"></span>${nav(1, "Next", "→")}</span>
        <span class="gallery-title"></span>
        <span class="gallery-hint" aria-hidden="true">click to enlarge</span>
        <p class="gallery-text" hidden></p>
      </figcaption>
    </figure>
    <ul class="gallery-strip"${many ? "" : " hidden"}>${thumbs}</ul>
  </div>`;
}

/* ---- Art ---- */

const coverOf = (s) => pics(s.cover)[s.coverAt ?? 0];

// Every Drive folder a collection draws from.
const folders = (s) => [
  ...[...(s.projects ?? []), ...(s.studies ?? []), ...(s.extra ? [s.extra] : [])].map((x) => x.images),
  ...(s.pairs ?? []).flatMap((p) => [p.before, p.after]),
];

const pieceCount = (s) => folders(s).reduce((n, key) => n + pics(key).length, 0);

function renderArt(main) {
  main.innerHTML = `
    <section class="zone zone--page">
      <div class="shell">
        ${crumbs([["Résumé", "index.html"], ["Art"]])}
        ${zoneHead(artIntro)}
      </div>

      <section class="gateways">
        <div class="shell">
          ${head(`${count(order.length, "collections")}`, "one page each")}
          <div class="gateway-grid">
            ${order
              .map((id) => {
                const s = series[id];
                const cover = coverOf(s);
                return `
                <a class="gateway frame" href="art/${id}.html">
                  <img class="gateway-cover" src="${cover.src}" alt="" loading="lazy" decoding="async"
                    ${s.coverPos ? `style="object-position: ${s.coverPos}"` : ""} />
                  <span class="gateway-index">${s.index}</span>
                  <span class="gateway-title">${s.title}</span>
                  <span class="gateway-note">${s.tagline}</span>
                  <span class="gateway-meta">${count(pieceCount(s), "pieces")}${s.status ? ` · ${s.status}` : ""}</span>
                  <span class="gateway-go" aria-hidden="true">open →</span>
                </a>`;
              })
              .join("")}
          </div>
        </div>
      </section>

      <section class="timeline-block">
        <div class="shell">
          ${head("How it happened", "2017 - today")}
          ${timeline(artTimeline)}
        </div>
      </section>

      <div class="shell">${pager("art.html", "")}</div>
    </section>`;
}

/* One block of a collection, laid out like a Code project page: the pieces
   first and as wide as the page, each with its caption under it, then the
   words, with the facts beside them when there are any. */
const piece = ({ id, title, meta, text, side, body }) => `
  <section class="piece" id="${id}">
    ${head(title, meta)}
    <div class="piece-media">${body}</div>
    <div class="piece-body${side ? " piece-body--side" : ""}">
      <div class="piece-text">${text}</div>
      ${side ? `<aside class="piece-side frame">${side}</aside>` : ""}
    </div>
  </section>`;

// A project, a study or the extra set: its pieces, its words and its facts.
function block(x) {
  const imgs = pics(x.images);
  return {
    id: x.id,
    title: x.title,
    html: piece({
      id: x.id,
      title: x.title,
      meta: count(imgs.length, "pieces"),
      text: `<p class="piece-lead">${x.note}</p>${paras(x.concept)}`,
      side: brief(x.brief),
      body: gallery(imgs, { label: x.title }),
    }),
  };
}

// Before and after, side by side, the older half quieter.
const pairBlock = (pair) => ({
  id: pair.id,
  title: pair.title,
  html: piece({
    id: pair.id,
    title: pair.title,
    meta: "before → now",
    text: `<p>${pair.note}</p>`,
    body: `
      <div class="pair-grid">
        <div class="pair-side">
          <span class="pair-tag">Before</span>
          ${gallery(pics(pair.before), { label: `${pair.title} · before`, compact: true })}
        </div>
        <div class="pair-arrow" aria-hidden="true">→</div>
        <div class="pair-side">
          <span class="pair-tag pair-tag--now">Now</span>
          ${gallery(pics(pair.after), { label: `${pair.title} · now`, compact: true })}
        </div>
      </div>`,
  }),
});

const seriesBlocks = (s) =>
  [
    { name: "Projects", blocks: s.projects?.map(block) },
    { name: "Studies", blocks: s.studies?.map(block) },
    { name: "Before → now", blocks: s.pairs?.map(pairBlock) },
    { name: "More", blocks: s.extra && [block(s.extra)] },
  ].filter((g) => g.blocks);

// Everything in the collection, one click away, before any of it scrolls by.
const jump = (groups) => `
  <nav class="jump" aria-label="In this collection">
    ${groups
      .map(
        (g) => `
      <div class="jump-group">
        <span class="jump-label">${g.name}</span>
        <ul class="jump-links">${g.blocks
          .map((b) => `<li><a href="#${b.id}">${b.title}</a></li>`)
          .join("")}</ul>
      </div>`,
      )
      .join("")}
  </nav>`;

function renderSeries(main, id) {
  const s = series[id];
  if (!s) return;
  const groups = seriesBlocks(s);

  main.innerHTML = `
    <section class="zone zone--page">
      <div class="shell">
        ${crumbs([["Résumé", "../index.html"], ["Art", "../art.html"], [s.title]])}
        ${zoneHead({ ...s, body: null })}
        <div class="intro-grid">
          <div class="intro-body">
            ${paras(s.body)}
            ${jump(groups)}
          </div>
          ${s.brief ? `<aside class="intro-side frame">${brief(s.brief)}</aside>` : ""}
        </div>
        ${groups.flatMap((g) => g.blocks.map((b) => b.html)).join("")}
        ${pager(`art/${id}.html`, "../")}
      </div>
    </section>`;
}

/* ---- Code ---- */

/* A project page shows only the screens from its Drive folder. `screens`
   in code.js picks their order, names and captions: each entry is a file's
   slug (its id in images.js), the label to show and what the screen does. */
const screensOf = (p) => {
  const all = pics(p.shots);
  if (!p.screens) return all;
  return p.screens.map(([id, label, caption]) => {
    const pic = all.find((x) => x.id === id);
    if (!pic) throw new Error(`${p.id}: no screen "${id}" in ${p.shots}`);
    return { ...pic, label, caption };
  });
};

// The picture behind a project's card: its own cover, or its first screen.
const coverFor = (p) => covers[p.id] ?? screensOf(p)[0]?.src;

const card = (p) => `
  <article class="card frame">
    <div class="card-media">
      <img src="${coverFor(p)}" alt="Screenshot of ${p.title}" loading="lazy" decoding="async" />
    </div>
    <div class="card-body">
      <div class="card-head">
        ${marks[p.id] ? `<img class="card-mark" src="${marks[p.id]}" alt="" />` : ""}
        <h3><a class="card-link" href="code/${p.id}.html">${p.title}</a></h3>
      </div>
      <p>${p.tagline}</p>
      <div class="card-links">${ext(p.repo, "code", "")}${p.live ? ext(p.live, "live", "") : ""}</div>
    </div>
  </article>`;

/* The apps, laid out like the résumé's experience cards: the screen on the
   right, fading into the project's own colour, the words on the left and
   the app's mark in the corner. The whole card opens the project page; the
   mark opens the app itself, or its code when there is no live site. */
const appCard = (p) => `
  <article class="entry entry--card entry--side" id="${p.id}" style="--c: ${p.hue}">
    <img class="entry-bg" src="${coverFor(p)}" alt="" loading="lazy" decoding="async" />
    <a class="entry-cover" href="code/${p.id}.html" tabindex="-1" aria-hidden="true"></a>
    ${
      marks[p.id]
        ? `<a class="entry-logo-link" href="${p.live ?? p.repo}" target="_blank" rel="noopener"
        aria-label="${p.title} ${p.live ? "live site" : "code"}" title="${p.live ? "Open the live site" : "Open the code"}">
      <img class="entry-logo entry-logo--mark" src="${marks[p.id]}" alt="${p.title}" loading="lazy" decoding="async" /></a>`
        : ""
    }
    <div class="entry-panel">
      <div class="entry-when">
        <span class="entry-dates">${p.when}</span>
        <span class="entry-place">${p.origin}</span>
        <span class="entry-flag">${p.live ? "live" : "own server"}</span>
      </div>
      <div class="entry-main">
        <h3 class="entry-role"><a href="code/${p.id}.html">${p.title}</a></h3>
        <p class="entry-org">${p.tagline}</p>
        <p>${p.lead}</p>
        <ul class="entry-notes">${p.shows.map((x) => `<li>${x}</li>`).join("")}</ul>
        <ul class="tag-row">${p.stack.map((x) => `<li class="tag">${x}</li>`).join("")}</ul>
        <p class="entry-link">
          <a class="text-link" href="code/${p.id}.html">Project page →</a>
          ${ext(p.repo, "code ↗")}
          ${p.live ? ext(p.live, "live ↗") : ""}
        </p>
      </div>
    </div>
  </article>`;

/* ---- The path so far ----
   One stage per section of the curriculum, each with its own axis. Dates
   become positions on that axis (0 to 1); the labels under the bars are
   stacked into rows by src/path.js once their widths are known. */

const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

const dayOf = (d) => {
  if (d === "today") return Date.now();
  const [y, m, day = 1] = d.split("-").map(Number);
  return Date.UTC(y, m - 1, day);
};

const parts = (d) => {
  const t = new Date(dayOf(d));
  return { y: t.getUTCFullYear(), m: t.getUTCMonth(), d: t.getUTCDate() };
};

// "Jul", or "mid Jan" when a date falls inside the month.
const monthName = ({ m, d }) => `${d >= 10 ? "mid " : ""}${MONTHS[m]}`;

function span(from, to) {
  const a = parts(from);
  if (to === "today") return `${monthName(a)} ${a.y} - today`;
  const b = parts(to);
  return a.y === b.y
    ? `${monthName(a)} - ${monthName(b)} ${b.y}`
    : `${monthName(a)} ${a.y} - ${monthName(b)} ${b.y}`;
}

const tickName = (d) => {
  const { m, d: day } = parts(d);
  return day === 1 ? MONTHS[m] : `${day} ${MONTHS[m]}`;
};

// Every 1st of the month on the axis, plus the first day when it is not one.
function ticksOf(stage) {
  if (stage.ticks) return stage.ticks;
  const list = [];
  const a = parts(stage.from);
  if (a.d !== 1) list.push(stage.from);
  const end = dayOf(stage.to);
  for (let y = a.y, m = a.m + (a.d === 1 ? 0 : 1); ; m++) {
    const d = `${y + Math.floor(m / 12)}-${String((m % 12) + 1).padStart(2, "0")}`;
    if (dayOf(d) > end) break;
    list.push(d);
  }
  return list;
}

const pct = (n) => `${(n * 100).toFixed(2)}%`;

function renderStage(stage, i) {
  const t0 = dayOf(stage.from);
  const len = dayOf(stage.to) - t0;
  const at = (d) => Math.min(1, Math.max(0, (dayOf(d) - t0) / len));

  const point = (pt) => {
    const project = pt.project && projects.find((x) => x.id === pt.project);
    const href = project ? `code/${project.id}.html` : pt.repo ? GH + pt.repo : pt.href;
    const external = /^https?:/.test(href);
    const when = pt.at === "today" ? "today" : `${tickName(pt.at)} ${parts(pt.at).y}`;
    return `
      <a class="gantt-point${external ? "" : " gantt-point--here"}" style="--x: ${pct(at(pt.at))}" data-x="${at(pt.at)}"
        href="${href}"${external ? ' target="_blank" rel="noopener"' : ""} title="${pt.label} · ${when}">
        <span class="gantt-label">${pt.label}${external ? " ↗" : ""}</span></a>`;
  };

  const track = (tr) => `
    <li class="gantt-row${tr.to === "today" ? " gantt-row--live" : ""}">
      <span class="gantt-name">${tr.name}</span>
      <div class="gantt-track" style="--rows: ${tr.points?.length ? 1 : 0}">
        <span class="gantt-bar" style="--a: ${pct(at(tr.from))}; --b: ${pct(at(tr.to))}"></span>
        ${(tr.points ?? []).map(point).join("")}
      </div>
    </li>`;

  const ticks = ticksOf(stage);
  return `
    <li class="stage${stage.to === "today" ? " stage--live" : ""}">
      <div class="stage-head">
        <span class="stage-index">${pad(i + 1)}</span>
        <h3 class="stage-title">${stage.title}</h3>
        <span class="stage-when">${span(stage.from, stage.to)}</span>
        ${stage.link ? ext(stage.link, "the course ↗") : ""}
      </div>
      <div class="stage-text">${paras(stage.text)}</div>
      <div class="gantt">
        <div class="gantt-axis" aria-hidden="true">${ticks
          .map(
            (d) =>
              `<span class="gantt-tick${at(d) > 0.97 ? " gantt-tick--end" : ""}" style="--x: ${pct(at(d))}">${tickName(d)}</span>`,
          )
          .join("")}${stage.to === "today" ? `<span class="gantt-tick gantt-tick--end" style="--x: 100%">today</span>` : ""}</div>
        <div class="gantt-lines" aria-hidden="true">${ticks
          .map((d) => `<span style="--x: ${pct(at(d))}"></span>`)
          .join("")}</div>
        <ul class="gantt-rows">${stage.tracks.map(track).join("")}</ul>
      </div>
    </li>`;
}

const pathSection = () => `
  <ol class="path">
    ${path.map(renderStage).join("")}
    <li class="stage stage--next">
      <div class="stage-head">
        <span class="stage-index">${pad(path.length + 1)}</span>
        <h3 class="stage-title">Coming soon</h3>
      </div>
      <div class="stage-text"><p>${nextUp.text}</p></div>
      <ul class="next-up">${nextUp.courses.map((c) => `<li>${c}</li>`).join("")}</ul>
    </li>
  </ol>`;

function renderCode(main) {
  const apps = projects.filter((p) => !p.practice);
  const practice = projects.filter((p) => p.practice);
  main.innerHTML = `
    <section class="zone zone--page">
      <div class="shell">
        ${crumbs([["Résumé", "index.html"], ["Code"]])}
        ${zoneHead({ ...codeIntro, stacked: true })}
      </div>

      <section class="work">
        <div class="shell">
          ${head("Projects", `${count(apps.length, "apps & games")} · one page each`)}

          <div class="entries entries--apps">${apps.map(appCard).join("")}</div>

          <div class="practice">
            ${head("Practice", `${count(practice.length, "exercises")} · algorithms &amp; data structures`)}
            <p class="practice-note">
              Smaller builds from the curriculum, each one a data structure or an
              algorithm written from scratch and given an interface you can poke at.
            </p>
          </div>
          <div class="work-grid work-grid--practice">
            ${practice.map(card).join("")}
            <a class="tile frame" href="${GH}" target="_blank" rel="noopener">
              <span class="tile-arrow" aria-hidden="true">↗</span>
              <span class="tile-title">More on GitHub</span>
              <span class="tile-meta">All repositories</span>
            </a>
          </div>
        </div>
      </section>

      <section class="timeline-block">
        <div class="shell">
          ${head("The path so far", `${span(path[0].from, "today")}`)}
          ${pathSection()}
        </div>
      </section>

      <section class="toolbox">
        <div class="shell">
          ${head("Toolbox", "what the work above runs on")}
          <dl class="tool-grid">
            ${toolbox.map(([k, v]) => `<div class="tool"><dt>${k}</dt><dd>${v}</dd></div>`).join("")}
          </dl>
        </div>
      </section>

      <div class="shell">${pager("code.html", "")}</div>
    </section>`;
}

function renderCodeProject(main, id) {
  const p = projects.find((x) => x.id === id);
  if (!p) return;
  const screens = screensOf(p);

  main.innerHTML = `
    <article class="zone zone--page project">
      <div class="shell">
        ${crumbs([["Résumé", "../index.html"], ["Code", "../code.html"], [p.title]])}
        <header class="project-head">
          <div class="project-title-row">
            ${marks[p.id] ? `<img class="project-mark" src="${marks[p.id]}" alt="" />` : ""}
            <h1 class="project-title">${p.title}</h1>
          </div>
          <p class="project-tagline">${p.tagline}</p>
          <p class="project-lead">${p.lead}</p>
          <div class="project-actions">
            ${p.live ? ext(p.live, "Open the live version ↗", "button") : ""}
            ${ext(p.repo, "Read the code ↗", "button button--ghost")}
          </div>
        </header>

        <section class="series-block">
          ${head("Screens", `${count(screens.length, "screens")}`)}
          ${gallery(screens, { label: p.title })}
        </section>

        <div class="project-grid">
          <div class="project-notes">
            ${p.notes.map(([h, t]) => `<section class="note"><h2>${h}</h2><p>${t}</p></section>`).join("")}
          </div>
          <aside class="project-side frame">
            ${
              p.shows
                ? `<h2 class="side-title">What it shows</h2>
            <ul class="shows">${p.shows.map((x) => `<li>${x}</li>`).join("")}</ul>`
                : ""
            }
            <h2 class="side-title">Built with</h2>
            <ul class="chips">${p.stack.map((s) => `<li class="chip">${s}</li>`).join("")}</ul>
            <h2 class="side-title">Links</h2>
            <ul class="link-col">
              <li>${ext(p.repo, "Repository ↗")}</li>
              ${p.live ? `<li>${ext(p.live, "Live version ↗")}</li>` : ""}
            </ul>
          </aside>
        </div>

        ${pager(`code/${p.id}.html`, "../")}
      </div>
    </article>`;
}

/* ---- Timeline ---- */

function timeline(t) {
  // The whole row is the link when there is somewhere to go.
  const item = (it) => `
      <li class="tl-item${it.live ? " tl-item--live" : ""}${it.href ? " tl-item--link" : ""}"
          style="--from: ${it.from}; --to: ${it.to}">
        <span class="tl-when">${it.when}</span>
        ${it.href ? `<a class="tl-what" href="${it.href}">${it.what}</a>` : `<span class="tl-what">${it.what}</span>`}
        <span class="tl-where">${it.where}</span>
      </li>`;
  return `
    <div class="timeline" style="--cols: ${t.years.length}">
      <div class="tl-years" aria-hidden="true">${t.years.map((y) => `<span>${y}</span>`).join("")}</div>
      ${t.lanes
        .map(
          (lane) => `
        <div class="tl-lane">
          <h3 class="tl-lane-name">${lane.name}</h3>
          <ul class="tl-track">${lane.items.map(item).join("")}</ul>
        </div>`,
        )
        .join("")}
    </div>`;
}

const VIEWS = {
  art: renderArt,
  series: renderSeries,
  code: renderCode,
  "code-project": renderCodeProject,
};

export function renderPage() {
  const main = document.querySelector("main[data-view]");
  if (main) VIEWS[main.dataset.view]?.(main, main.dataset.id);

  // The page was empty when the browser looked for #anchor; look again.
  if (main && location.hash) document.getElementById(location.hash.slice(1))?.scrollIntoView();
}
