import { intro as artIntro, series, order, artTimeline } from "./content/art.js";
import { intro as codeIntro, projects, toolbox, codeTimeline } from "./content/code.js";
import { covers, marks } from "./content/media.js";
import { pics } from "./content/pics.js";
import { ratioOf, stageImg } from "./gallery.js";

/* Fills every Art and Code page from src/content/. The HTML files are
   generated by src/layout.js and only carry the chrome plus a hook:
     <main data-view="art">                     the Art overview
     <main data-view="series" data-id="msr">    one collection
     <main data-view="code">                    the Code overview
     <main data-view="code-project" data-id="…"> one project
   plus <div data-timeline="…"> wherever a timeline goes. Everything here runs
   before motion.js, so reveals see the finished DOM. */

const pad = (n) => String(n).padStart(2, "0");
const count = (n, word) => `${pad(n)} ${word}`;
const paras = (list = []) => list.map((p) => `<p>${p}</p>`).join("");

const media = (img, alt = img.alt ?? img.label) =>
  img.src
    ? `<img src="${img.src}" alt="${alt}" loading="lazy" decoding="async" />`
    : `<div class="ph ph--${img.ratio}"><span>${img.label}</span></div>`;

const crumbs = (trail) => `
  <nav class="crumbs" aria-label="Breadcrumb">
    ${trail
      .map(([name, href]) =>
        href ? `<a href="${href}">${name}</a>` : `<span aria-current="page">${name}</span>`,
      )
      .join('<span class="crumb-sep" aria-hidden="true">/</span>')}
  </nav>`;

const brief = (rows = []) =>
  rows.length
    ? `<dl class="brief">${rows
        .map(([k, v]) => `<div class="brief-row"><dt>${k}</dt><dd>${v}</dd></div>`)
        .join("")}</dl>`
    : "";

const head = (title, meta = "") => `
  <div class="block-head"><h2>${title}</h2><span class="block-meta">${meta}</span></div>`;

/* The whole site read front to back: every section page knows what comes
   before and after it. Paths are from the site root. */
const TRAIL = [
  { href: "art.html", name: "Art" },
  ...order.map((id) => ({ href: `art/${id}.html`, name: series[id].title })),
  { href: "code.html", name: "Code" },
  ...projects.map((p) => ({ href: `code/${p.id}.html`, name: p.title })),
];

function pager(here, root) {
  const i = TRAIL.findIndex((t) => t.href === here);
  const prev = TRAIL[i - 1] ?? { href: "index.html", name: "Résumé" };
  const next = TRAIL[i + 1] ?? { href: "index.html#contact", name: "Get in touch" };
  const link = (t, dir, cls) => `
    <a class="pager-link ${cls}" href="${root}${t.href}">
      <span class="pager-dir">${dir}</span>
      <span class="pager-name">${t.name}</span></a>`;
  return `
  <nav class="pager" aria-label="Pagination">
    ${link(prev, "← Previous", "pager-prev")}
    ${link(next, "Next →", "pager-next")}
  </nav>`;
}

// Page title block shared by both overviews and every collection.
const zoneHead = ({ index, title, lead, body, status, stats }) => `
  <div class="zone-head${body ? " zone-head--split" : ""}">
    <div class="zone-head-main">
      ${status ? `<span class="case-status">${status}</span>` : ""}
      <span class="zone-index" aria-hidden="true">${index}</span>
      <h1 class="zone-title">${title}</h1>
      <p class="zone-lead">${lead}</p>
    </div>
    ${body ? `<div class="zone-body">${paras(body)}</div>` : ""}
    ${
      stats
        ? `<ul class="stat-row">${stats
            .map(
              ([v, l]) =>
                `<li class="stat"><span class="stat-value">${v}</span><span class="stat-label">${l}</span></li>`,
            )
            .join("")}</ul>`
        : ""
    }
  </div>`;

/* A set of pieces as a stage and a strip (behaviour in src/gallery.js). The
   stage keeps one shape for the whole set, picked from the pieces themselves,
   so flicking through them never makes the page jump; each piece sits inside
   it at its own proportions. Its caption only exists in the lightbox. */
const esc = (t = "") => t.replace(/"/g, "&quot;");

function gallery(images, { label = "", compact = false } = {}) {
  if (!images.length) return "";
  const ars = images.map(ratioOf).sort((a, b) => a - b);
  const stageAr = Math.min(1.78, Math.max(0.8, ars[Math.floor(ars.length / 2)]));
  const first = images[0];
  const thumbs = images
    .map(
      (img, i) => `
      <li><button type="button" class="gallery-thumb" style="--ar: ${ratioOf(img)}"
        data-title="${esc(img.label)}" data-caption="${esc(img.caption)}" data-ratio="${ratioOf(img)}"
        ${img.src ? `data-src="${img.src}"` : ""} ${img.full ? `data-full="${img.full}"` : ""} ${img.w ? `data-w="${img.w}"` : ""}
        aria-label="Show ${esc(img.label)}"${i === 0 ? ' aria-current="true"' : ""}>${media(img, "")}</button></li>`,
    )
    .join("");
  return `
  <div class="gallery${compact ? " gallery--compact" : ""}" data-lightbox="${esc(label)}" data-index="0">
    <figure class="gallery-stage">
      <button type="button" class="gallery-open" style="--stage-ar: ${stageAr}"
        aria-label="Open ${esc(first.label)} full screen">${
          first.src ? stageImg({ ...first, alt: first.label }) : media(first, "")
        }</button>
      <figcaption class="gallery-caption">
        <span class="gallery-count">01 / ${pad(images.length)}</span>
        <span class="gallery-title">${first.label}</span>
        <span class="gallery-hint" aria-hidden="true">click to enlarge</span>
      </figcaption>
    </figure>
    <ul class="gallery-strip"${images.length < 2 ? " hidden" : ""}>${thumbs}</ul>
  </div>`;
}

/* ---- Art ---- */

const coverOf = (s) => pics(s.cover)[s.coverAt ?? 0];

const pieceCount = (s) =>
  [
    ...(s.projects ?? []).map((p) => p.images),
    ...(s.studies ?? []).map((st) => st.images),
    ...(s.pairs ?? []).flatMap((p) => [p.before, p.after]),
    ...(s.extra ? [s.extra.images] : []),
  ].reduce((n, key) => n + pics(key).length, 0);

function renderArt(main) {
  main.innerHTML = `
    <section class="zone zone--page" data-zone="art">
      <div class="shell">
        ${crumbs([["Résumé", "index.html"], ["Art"]])}
        ${zoneHead(artIntro)}
      </div>

      <section class="gateways">
        <div class="shell">
          ${head(`${count(order.length, "collections")}`, "one page each")}
          <div class="gateway-grid">
            ${order
              .map((id) => {
                const s = series[id];
                const cover = coverOf(s);
                return `
                <a class="gateway frame" href="art/${id}.html">
                  <img class="gateway-cover" src="${cover.src}" alt="" loading="lazy" decoding="async"
                    ${s.coverPos ? `style="object-position: ${s.coverPos}"` : ""} />
                  <span class="gateway-index">${s.index}</span>
                  <span class="gateway-title">${s.title}</span>
                  <span class="gateway-note">${s.tagline}</span>
                  <span class="gateway-meta">${count(pieceCount(s), "pieces")}${s.status ? ` · ${s.status}` : ""}</span>
                  <span class="gateway-go" aria-hidden="true">open →</span>
                </a>`;
              })
              .join("")}
          </div>
        </div>
      </section>

      <section class="timeline-block">
        <div class="shell">
          ${head("How it happened", "2017 - today")}
          <div class="timeline" data-timeline="art"></div>
        </div>
      </section>

      <div class="shell">${pager("art.html", "")}</div>
    </section>`;
}

/* One block of a collection: the words on the left, the pieces on the right,
   so a project reads as a single spread instead of a page and a gallery. */
const piece = ({ id, title, meta, text, body, wide }) => `
  <section class="piece${wide ? " piece--wide" : ""}" id="${id}">
    ${head(title, meta)}
    <div class="piece-body">
      <div class="piece-text">${text}</div>
      <div class="piece-media">${body}</div>
    </div>
  </section>`;

function seriesBlocks(s) {
  const groups = [];

  if (s.projects) {
    groups.push({
      name: "Projects",
      blocks: s.projects.map((p) => {
        const imgs = pics(p.images);
        return {
          id: p.id,
          title: p.title,
          html: piece({
            id: p.id,
            title: p.title,
            meta: count(imgs.length, "pieces"),
            text: `<p class="piece-lead">${p.note}</p>${paras(p.concept)}${brief(p.brief)}`,
            body: gallery(imgs, { label: p.title }),
          }),
        };
      }),
    });
  }

  if (s.studies) {
    groups.push({
      name: "Studies",
      blocks: s.studies.map((st) => {
        const imgs = pics(st.images);
        return {
          id: st.id,
          title: st.title,
          html: piece({
            id: st.id,
            title: st.title,
            meta: count(imgs.length, "pieces"),
            text: `<p class="piece-lead">${st.note}</p>`,
            body: gallery(imgs, { label: st.title }),
          }),
        };
      }),
    });
  }

  if (s.pairs) {
    groups.push({
      name: "Before → now",
      blocks: s.pairs.map((pair) => ({
        id: pair.id,
        title: pair.title,
        html: piece({
          id: pair.id,
          title: pair.title,
          meta: "before → now",
          wide: true,
          text: `<p>${pair.note}</p>`,
          body: `
            <div class="pair-grid">
              <div class="pair-side">
                <span class="pair-tag">Before</span>
                ${gallery(pics(pair.before), { label: `${pair.title} · before`, compact: true })}
              </div>
              <div class="pair-arrow" aria-hidden="true">→</div>
              <div class="pair-side">
                <span class="pair-tag pair-tag--now">Now</span>
                ${gallery(pics(pair.after), { label: `${pair.title} · now`, compact: true })}
              </div>
            </div>`,
        }),
      })),
    });
  }

  if (s.extra) {
    const imgs = pics(s.extra.images);
    groups.push({
      name: "More",
      blocks: [
        {
          id: s.extra.id,
          title: s.extra.title,
          html: piece({
            id: s.extra.id,
            title: s.extra.title,
            meta: count(imgs.length, "pieces"),
            text: `<p class="piece-lead">${s.extra.note}</p>`,
            body: gallery(imgs, { label: s.extra.title }),
          }),
        },
      ],
    });
  }

  return groups;
}

// Everything in the collection, one click away, before any of it scrolls by.
const jump = (groups) => `
  <nav class="jump" aria-label="In this collection">
    ${groups
      .map(
        (g) => `
      <div class="jump-group">
        <span class="jump-label">${g.name}</span>
        <ul class="jump-links">${g.blocks
          .map((b) => `<li><a href="#${b.id}">${b.title}</a></li>`)
          .join("")}</ul>
      </div>`,
      )
      .join("")}
  </nav>`;

function renderSeries(main, id) {
  const s = series[id];
  if (!s) return;
  const groups = seriesBlocks(s);

  main.innerHTML = `
    <section class="zone zone--page" data-zone="art">
      <div class="shell">
        ${crumbs([["Résumé", "../index.html"], ["Art", "../art.html"], [s.title]])}
        ${zoneHead({ ...s, body: null })}
        <div class="intro-grid">
          <div class="intro-body">
            ${paras(s.body)}
            ${jump(groups)}
          </div>
          ${s.brief ? `<aside class="intro-side frame">${brief(s.brief)}</aside>` : ""}
        </div>
        ${groups.flatMap((g) => g.blocks.map((b) => b.html)).join("")}
        ${pager(`art/${id}.html`, "../")}
      </div>
    </section>`;
}

/* ---- Code ---- */

const coverFor = (p) => covers[p.id] ?? pics(p.shots)[0]?.src;

// A project's own cover leads its screens, when it has one.
const screensOf = (p) => [
  ...(covers[p.id] ? [{ src: covers[p.id], label: p.title, ar: 16 / 10, caption: p.tagline }] : []),
  ...pics(p.shots),
];

const codeLinks = (p) => `
  <div class="card-links">
    <a href="${p.repo}" target="_blank" rel="noopener">code</a>
    ${p.live ? `<a href="${p.live}" target="_blank" rel="noopener">live</a>` : ""}
  </div>`;

const projectHead = (p, inner) => `
  <div class="card-head">
    ${marks[p.id] ? `<img class="card-mark" src="${marks[p.id]}" alt="" />` : ""}
    <h3><a class="card-link" href="code/${p.id}.html">${p.title}</a></h3>
  </div>${inner}`;

const card = (p) => `
  <article class="card frame">
    <div class="card-media">
      <img src="${coverFor(p)}" alt="Screenshot of ${p.title}" loading="lazy" decoding="async" />
    </div>
    <div class="card-body">
      ${projectHead(p, `<p>${p.tagline}</p>${codeLinks(p)}`)}
    </div>
  </article>`;

function renderCode(main) {
  const featured = projects.filter((p) => !p.practice);
  const practice = projects.filter((p) => p.practice);
  const [lead, ...rest] = featured;
  main.innerHTML = `
    <section class="zone zone--page" data-zone="code">
      <div class="shell">
        ${crumbs([["Résumé", "index.html"], ["Code"]])}
        ${zoneHead(codeIntro)}
      </div>

      <section class="work">
        <div class="shell">
          ${head("Projects", `${count(featured.length, "apps & games")} · one page each`)}

          <article class="featured frame">
            <div class="featured-media">
              <img src="${coverFor(lead)}" alt="Screenshot of ${lead.title}" />
            </div>
            <div class="featured-body">
              ${projectHead(lead, `<p>${lead.tagline} ${lead.lead}</p>${codeLinks(lead)}`)}
            </div>
          </article>

          <div class="work-grid">${rest.map(card).join("")}</div>

          <div class="practice">
            ${head("Practice", `${count(practice.length, "exercises")} · algorithms &amp; data structures`)}
            <p class="practice-note">
              Smaller builds from the curriculum, each one a data structure or an
              algorithm written from scratch and given an interface you can poke at.
            </p>
          </div>
          <div class="work-grid work-grid--practice">
            ${practice.map(card).join("")}
            <a class="tile frame" href="https://github.com/AndreaGarzoglio" target="_blank" rel="noopener">
              <span class="tile-arrow" aria-hidden="true">↗</span>
              <span class="tile-title">More on GitHub</span>
              <span class="tile-meta">All repositories</span>
            </a>
          </div>
        </div>
      </section>

      <section class="timeline-block">
        <div class="shell">
          ${head("The path so far", `${codeTimeline.years[0]} - today`)}
          <div class="timeline" data-timeline="code"></div>
        </div>
      </section>

      <section class="toolbox">
        <div class="shell">
          ${head("Toolbox", "what the work above runs on")}
          <dl class="tool-grid">
            ${toolbox.map(([k, v]) => `<div class="tool"><dt>${k}</dt><dd>${v}</dd></div>`).join("")}
          </dl>
        </div>
      </section>

      <div class="shell">${pager("code.html", "")}</div>
    </section>`;
}

function renderCodeProject(main, id) {
  const p = projects.find((x) => x.id === id);
  if (!p) return;
  const link = (href, label, cls = "button") =>
    `<a class="${cls}" href="${href}" target="_blank" rel="noopener">${label}</a>`;

  main.innerHTML = `
    <article class="zone zone--page project" data-zone="code">
      <div class="shell">
        ${crumbs([["Résumé", "../index.html"], ["Code", "../code.html"], [p.title]])}
        <header class="project-head">
          ${marks[p.id] ? `<img class="project-mark" src="${marks[p.id]}" alt="" />` : ""}
          <h1 class="project-title">${p.title}</h1>
          <p class="project-tagline">${p.tagline}</p>
          <p class="project-lead">${p.lead}</p>
          <div class="project-actions">
            ${p.live ? link(p.live, "Open the live version ↗") : `<p class="entry-meta">${p.liveNote ?? ""}</p>`}
            ${link(p.repo, "Read the code ↗", "button button--ghost")}
          </div>
        </header>

        <section class="series-block">
          ${head("Screens", `${count(screensOf(p).length, "screens")}`)}
          ${gallery(screensOf(p), { label: p.title })}
        </section>

        <div class="project-grid">
          <div class="project-notes">
            ${p.notes.map(([h, t]) => `<section class="note"><h2>${h}</h2><p>${t}</p></section>`).join("")}
          </div>
          <aside class="project-side frame">
            ${
              p.shows
                ? `<h2 class="side-title">What it shows</h2>
            <ul class="shows">${p.shows.map((x) => `<li>${x}</li>`).join("")}</ul>`
                : ""
            }
            <h2 class="side-title">Built with</h2>
            <ul class="chips">${p.stack.map((s) => `<li class="chip">${s}</li>`).join("")}</ul>
            <h2 class="side-title">Links</h2>
            <ul class="link-col">
              <li>${link(p.repo, "Repository ↗", "text-link")}</li>
              ${p.live ? `<li>${link(p.live, "Live version ↗", "text-link")}</li>` : ""}
            </ul>
          </aside>
        </div>

        ${pager(`code/${p.id}.html`, "../")}
      </div>
    </article>`;
}

/* ---- Timelines ---- */

const TIMELINES = { art: artTimeline, code: codeTimeline };

function renderTimeline(el) {
  const t = TIMELINES[el.dataset.timeline];
  if (!t) return;
  el.style.setProperty("--cols", t.years.length);
  // The whole row is the link when there is somewhere to go.
  const item = (it) => `
      <li class="tl-item${it.live ? " tl-item--live" : ""}${it.href ? " tl-item--link" : ""}"
          style="--from: ${it.from}; --to: ${it.to}">
        <span class="tl-when">${it.when}</span>
        ${it.href ? `<a class="tl-what" href="${it.href}">${it.what}</a>` : `<span class="tl-what">${it.what}</span>`}
        <span class="tl-where">${it.where}</span>
      </li>`;
  el.innerHTML = `
    <div class="tl-years" aria-hidden="true">${t.years.map((y) => `<span>${y}</span>`).join("")}</div>
    ${t.lanes
      .map(
        (lane) => `
        <div class="tl-lane">
          <h3 class="tl-lane-name">${lane.name}</h3>
          <ul class="tl-track">${lane.items.map(item).join("")}</ul>
        </div>`,
      )
      .join("")}`;
}

const VIEWS = {
  art: renderArt,
  series: renderSeries,
  code: renderCode,
  "code-project": renderCodeProject,
};

export function renderPage() {
  const main = document.querySelector("main[data-view]");
  if (main) VIEWS[main.dataset.view]?.(main, main.dataset.id);
  document.querySelectorAll("[data-timeline]").forEach(renderTimeline);

  // The page was empty when the browser looked for #anchor; look again.
  if (main && location.hash) document.getElementById(location.hash.slice(1))?.scrollIntoView();
}
