import { intro as artIntro, series, order } from "./content/art.js";
import {
  intro as codeIntro,
  projects,
  toolbox,
  path,
  nextUp,
  GH,
} from "./content/code.js";
import { covers, marks, artLogos } from "./content/media.js";
import { pics } from "./content/pics.js";
import { pad, esc, ext } from "./html.js";
import { t } from "./i18n.js";

/* Fills every Art and Code page from src/content/. The HTML files are
   generated by src/layout.js and only carry the chrome plus a hook:
     <main data-view="art">                     the Art overview
     <main data-view="series" data-id="msr">    one collection
     <main data-view="code">                    the Code overview
     <main data-view="code-project" data-id="…"> one project
   Everything here runs before motion.js, so reveals see the finished DOM. */

const count = (n, word) => `${pad(n)} ${t(word)}`;
const paras = (list = []) => list.map((p) => `<p>${p}</p>`).join("");

const crumbs = (trail) => `
  <nav class="crumbs" aria-label="Breadcrumb">
    ${trail
      .map(([name, href]) =>
        href
          ? `<a href="${href}">${name}</a>`
          : `<span aria-current="page">${name}</span>`,
      )
      .join('<span class="crumb-sep" aria-hidden="true">/</span>')}
  </nav>`;

const brief = (rows = []) =>
  rows.length
    ? `<dl class="brief">${rows
        .map(
          ([k, v]) => `<div class="brief-row"><dt>${k}</dt><dd>${v}</dd></div>`,
        )
        .join("")}</dl>`
    : "";

const head = (title, meta = "") => `
  <div class="block-head"><h2>${title}</h2><span class="block-meta">${meta}</span></div>`;

/* The whole site read front to back: every section page knows what comes
   before and after it. Paths are from the site root. */
const TRAIL = [
  { href: "art.html", name: "Art" },
  ...order.map((id) => ({ href: `art/${id}.html`, name: series[id].title })),
  { href: "code.html", name: "Code" },
  ...projects.map((p) => ({ href: `code/${p.id}.html`, name: p.title })),
];

function pager(here, root) {
  const i = TRAIL.findIndex((t) => t.href === here);
  const prev = TRAIL[i - 1] ?? { href: "index.html", name: "Résumé" };
  const next = TRAIL[i + 1] ?? {
    href: "index.html#contact",
    name: "Get in touch",
  };
  const link = (t, dir, cls) => `
    <a class="pager-link ${cls}" href="${root}${t.href}">
      <span class="pager-dir">${dir}</span>
      <span class="pager-name">${t.name}</span></a>`;
  return `
  <nav class="pager" aria-label="Pagination">
    ${link(prev, "← Previous", "pager-prev")}
    ${link(next, "Next →", "pager-next")}
  </nav>`;
}

/* Page title block shared by both overviews and every collection. The longer
   text sits beside the title on wide screens, or under it with `stacked`. */
const zoneHead = ({ index, title, lead, body, status, stats, stacked }) => `
  <div class="zone-head${body ? (stacked ? " zone-head--stacked" : " zone-head--split") : ""}">
    <div>
      ${status ? `<span class="case-status">${status}</span>` : ""}
      <span class="zone-index" aria-hidden="true">${index}</span>
      <h1 class="zone-title">${title}</h1>
      <p class="zone-lead">${lead}</p>
    </div>
    ${body ? `<div class="zone-body">${paras(body)}</div>` : ""}
    ${
      stats
        ? `<ul class="stat-row">${stats
            .map(
              ([v, l]) =>
                `<li class="stat"><span class="stat-value">${v}</span><span class="stat-label">${l}</span></li>`,
            )
            .join("")}</ul>`
        : ""
    }
  </div>`;

// What the lightbox reads off any piece, in a gallery or a collage.
const pieceData = (img) =>
  `data-ratio="${img.ar}" data-title="${esc(img.label)}" data-caption="${esc(img.caption)}" data-full="${img.full}"`;

/* A set of pieces as a stage and a strip. This writes the frame and the
   strip; src/gallery.js puts a piece on the stage (show()) and runs it. The
   stage is always 16:9, so flicking through a set never makes the page
   jump, and a square or tall piece shrinks to fit inside it, never cropped. */
function gallery(images, { label = "" } = {}) {
  if (!images.length) return "";
  const many = images.length > 1;
  const nav = (step, name, arrow) =>
    many
      ? `<button type="button" class="gallery-nav" data-step="${step}" aria-label="${name}">${arrow}</button>`
      : "";
  const thumbs = images
    .map(
      (img) => `
      <li><button type="button" class="gallery-thumb" style="--ar: ${img.ar}" ${pieceData(img)}
        data-src="${img.src}" data-tw="${img.tw}" data-w="${img.w}"
        aria-label="${t("Show")} ${esc(img.label)}"><img src="${img.src}" alt="" loading="lazy" decoding="async" /></button></li>`,
    )
    .join("");
  return `
  <div class="gallery" data-lightbox="${esc(label)}" data-index="0">
    <figure class="gallery-stage">
      <button type="button" class="gallery-open"></button>
      <figcaption class="gallery-caption">
        <span class="gallery-steps">${nav(-1, "Previous", "←")}<span class="gallery-count"></span>${nav(1, "Next", "→")}</span>
        <span class="gallery-title"></span>
        <span class="gallery-hint" aria-hidden="true">click to enlarge</span>
        <p class="gallery-text" hidden></p>
      </figcaption>
    </figure>
    <ul class="gallery-strip"${many ? "" : " hidden"}>${thumbs}</ul>
  </div>`;
}

/* A set of pieces all at once and small, in rows that fill the width, each
   piece at its own proportions and with no frame around it. Any of them
   opens the lightbox on the whole set (src/lightbox.js). */
function collage(images, { label = "" } = {}) {
  if (!images.length) return "";
  const items = images
    .map(
      (img) => `
      <li style="--ar: ${img.ar}"><button type="button" class="collage-item" ${pieceData(img)}
        aria-label="${t("Enlarge")} ${esc(img.label)}"><img src="${img.src}" alt="" loading="lazy" decoding="async" /></button></li>`,
    )
    .join("");
  return `<ul class="collage" data-lightbox="${esc(label)}">${items}</ul>`;
}

/* A Code project or an Art collection on its overview, laid out like the
   résumé's experience cards: the picture on the right, fading into the
   card's own colour, the words on the left and a mark in the corner. The
   whole card opens the page; the mark leads somewhere of its own. With
   `frame` (the résumé card's --pos, --zoom and --origin) the picture covers
   the whole card instead, cropped in on its subject. */
const pageCard = ({
  id,
  href,
  hue,
  bg,
  pos,
  frame,
  logo,
  when,
  place,
  flag,
  title,
  tagline,
  lead,
  notes,
  tags,
  links,
}) => `
  <article class="entry entry--card${frame ? "" : " entry--side"}" id="${id}" style="--c: ${hue}${pos ? `; --pos: ${pos}` : ""}${frame ? `; ${frame}` : ""}">
    <img class="entry-bg" src="${bg}" alt="" loading="lazy" decoding="async" />
    <a class="entry-cover" href="${href}" tabindex="-1" aria-hidden="true"></a>
    ${
      logo
        ? `<a class="entry-logo-link" href="${logo.href}" target="_blank" rel="noopener"
        aria-label="${logo.label}" title="${logo.label}">
      <img class="entry-logo${logo.cls ? ` ${logo.cls}` : ""}" src="${logo.src}" alt="${logo.alt}" loading="lazy" decoding="async" /></a>`
        : ""
    }
    <div class="entry-panel">
      <div class="entry-when">
        <span class="entry-dates">${when}</span>
        <span class="entry-place">${place}</span>
        <span class="entry-flag">${flag}</span>
      </div>
      <div class="entry-main">
        <h3 class="entry-role"><a href="${href}">${title}</a></h3>
        <p class="entry-org">${tagline}</p>
        <p>${lead}</p>
        <ul class="entry-notes">${notes.map((x) => `<li>${x}</li>`).join("")}</ul>
        <ul class="tag-row">${tags.map((x) => `<li class="tag">${x}</li>`).join("")}</ul>
        <p class="entry-link">${links}</p>
      </div>
    </div>
  </article>`;

/* ---- Art ---- */

const coverOf = (s) => pics(s.cover)[s.coverAt ?? 0];

const artCard = (id) => {
  const s = series[id];
  const logo = artLogos[id];
  return pageCard({
    ...s.card,
    id,
    hue: s.hue,
    href: `art/${id}.html`,
    bg: coverOf(s).full,
    pos: s.coverPos,
    logo: logo && { ...logo, cls: logo.round ? "entry-logo--round" : "" },
    title: s.title,
    tagline: s.tagline,
    links: `<a class="text-link" href="art/${id}.html">Collection page →</a>`,
  });
};

function renderArt(main) {
  main.innerHTML = `
    <section class="zone zone--page">
      <div class="shell">
        ${crumbs([["Résumé", "index.html"], ["Art"]])}
        ${zoneHead({ ...artIntro, stacked: true })}
      </div>

      <section class="work">
        <div class="shell">
          ${head("Collections", `${count(order.length, "collections")} · ${t("one page each")}`)}
          <div class="entries entries--pages">${order.map(artCard).join("")}</div>
        </div>
      </section>

      <div class="shell">${pager("art.html", "")}</div>
    </section>`;
}

/* One block of a collection, laid out like a Code project page: the pieces
   first and as wide as the page, each with its caption under it, then the
   words, with the facts beside them when there are any. */
const piece = ({ id, title, meta, text, side, body }) => `
  <section class="piece" id="${id}">
    ${head(title, meta)}
    <div class="piece-media">${body}</div>
    <div class="piece-body${side ? " piece-body--side" : ""}">
      <div class="piece-text">${text}</div>
      ${side ? `<aside class="piece-side frame">${side}</aside>` : ""}
    </div>
  </section>`;

// The pieces of a block from its folder: `only` or `skip` (file ids) narrow
// the folder down, and `first` names the piece that should open the set.
function select({ images, only, skip = [], first }) {
  const all = pics(images).filter((img) => (only ? only.includes(img.id) : !skip.includes(img.id)));
  const lead = all.filter((img) => img.id === first);
  return [...lead, ...all.filter((img) => !lead.includes(img))];
}

// One side of a before and after: its tag over a collage of its pieces.
const side = (title, tag, images) => `
  <span class="pair-tag">${tag}</span>
  ${collage(images, { label: `${title} · ${t(tag.toLowerCase())}` })}`;

// Where the facts would go, the design as it was before, small.
const beforeSide = (x) => `
  ${side(x.title, "Before", select(x.before))}
  ${x.before.note ? `<p class="before-note">${x.before.note}</p>` : ""}`;

// A project, a study or the extra set: its pieces, its words and its facts.
// A project can name and caption its own pieces (`pieces`, by file id). A
// collection with `captions: false` shows its pieces without the stage notes.
// `collage: true` lays the pieces out all at once instead of on a stage, and
// `before` puts an older version where the facts would be.
function block(x, captions) {
  const imgs = select(x).map((img) => {
    const [label = img.label, caption = img.caption] = (x.pieces?.[img.id] ?? []).map(t);
    return { ...img, label, caption: captions ? caption : "" };
  });
  return {
    id: x.id,
    title: x.title,
    html: piece({
      id: x.id,
      title: x.title,
      meta: count(imgs.length, "pieces"),
      text: `<p class="piece-lead">${x.note}</p>${paras(x.concept)}`,
      side: x.before ? beforeSide(x) : brief(x.brief),
      body: (x.collage ? collage : gallery)(imgs, { label: x.title }),
    }),
  };
}

// A thread of work read from where it started to where it is now: two
// collages, one above the other.
const pairBlock = (pair) => ({
  id: pair.id,
  title: pair.title,
  html: piece({
    id: pair.id,
    title: pair.title,
    meta: "before → now",
    text: `<p>${pair.note}</p>`,
    body: `
      <div class="pair-grid">
        <div class="pair-side">${side(pair.title, "Before", pics(pair.before))}</div>
        <div class="pair-side">${side(pair.title, "Now", pics(pair.after))}</div>
      </div>`,
  }),
});

const seriesBlocks = (s) => {
  const blockOf = (x) => block(x, s.captions !== false);
  return [
    { name: "Projects", blocks: s.projects?.map(blockOf) },
    { name: "Studies", blocks: s.studies?.map(blockOf) },
    { name: "Before → now", blocks: s.pairs?.map(pairBlock) },
    { name: "More", blocks: s.extra && [blockOf(s.extra)] },
  ].filter((g) => g.blocks);
};

// Everything in the collection, one click away, before any of it scrolls by.
const jump = (groups) => `
  <nav class="jump" aria-label="In this collection">
    ${groups
      .map(
        (g) => `
      <div class="jump-group">
        <span class="jump-label">${g.name}</span>
        <ul class="jump-links">${g.blocks
          .map((b) => `<li><a href="#${b.id}">${b.title}</a></li>`)
          .join("")}</ul>
      </div>`,
      )
      .join("")}
  </nav>`;

function renderSeries(main, id) {
  const s = series[id];
  if (!s) return;
  const groups = seriesBlocks(s);

  main.innerHTML = `
    <section class="zone zone--page">
      <div class="shell">
        ${crumbs([["Résumé", "../index.html"], ["Art", "../art.html"], [s.title]])}
        ${zoneHead({ ...s, body: null })}
        <div class="intro-grid">
          <div class="intro-body">
            ${paras(s.body)}
            ${jump(groups)}
          </div>
          ${s.brief ? `<aside class="intro-side frame">${brief(s.brief)}</aside>` : ""}
        </div>
        ${groups.flatMap((g) => g.blocks.map((b) => b.html)).join("")}
        ${pager(`art/${id}.html`, "../")}
      </div>
    </section>`;
}

/* ---- Code ---- */

/* A project page shows only the screens from its Drive folder. `screens`
   in code.js picks their order, names and captions: each entry is a file's
   slug (its id in images.js), the label to show and what the screen does. */
const screensOf = (p) => {
  const all = pics(p.shots);
  if (!p.screens) return all;
  return p.screens.map(([id, label, caption]) => {
    const pic = all.find((x) => x.id === id);
    if (!pic) throw new Error(`${p.id}: no screen "${id}" in ${p.shots}`);
    return { ...pic, label: t(label), caption: t(caption) };
  });
};

// The picture behind a project's card: its own cover, or its first screen.
const coverFor = (p) => covers[p.id] ?? screensOf(p)[0]?.src;

const card = (p) => `
  <article class="card frame">
    <div class="card-media">
      <img src="${coverFor(p)}" alt="${t("Screenshot of")} ${p.title}" loading="lazy" decoding="async" />
    </div>
    <div class="card-body">
      <div class="card-head">
        ${marks[p.id] ? `<img class="card-mark" src="${marks[p.id]}" alt="" />` : ""}
        <h3><a class="card-link" href="code/${p.id}.html">${p.title}</a></h3>
      </div>
      <p>${p.tagline}</p>
      <div class="card-links">${ext(p.repo, "code", "")}${p.live ? ext(p.live, "live", "") : ""}</div>
    </div>
  </article>`;

const appCard = (p) =>
  pageCard({
    id: p.id,
    href: `code/${p.id}.html`,
    hue: p.hue,
    bg: coverFor(p),
    logo: marks[p.id] && {
      src: marks[p.id],
      alt: p.title,
      href: p.live ?? p.repo,
      label: `${p.title} · ${t(p.live ? "live site" : "code")}`,
      cls: "entry-logo--mark",
    },
    when: p.when,
    place: p.origin,
    flag: p.live ? "live" : "own server",
    title: p.title,
    tagline: p.tagline,
    lead: p.lead,
    notes: p.shows,
    tags: p.stack,
    links: `<a class="text-link" href="code/${p.id}.html">Project page →</a>
          ${ext(p.repo, "code ↗")}
          ${p.live ? ext(p.live, "live ↗") : ""}`,
  });

/* ---- The path so far ----
   One stage per section of the curriculum, each with its own axis. Dates
   become positions on that axis (0 to 1); the labels under the bars are
   stacked into rows by src/path.js once their widths are known. */

const MONTHS = "Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" ");

const dayOf = (d) => {
  if (d === "today") return Date.now();
  const [y, m, day = 1] = d.split("-").map(Number);
  return Date.UTC(y, m - 1, day);
};

const parts = (d) => {
  const t = new Date(dayOf(d));
  return { y: t.getUTCFullYear(), m: t.getUTCMonth(), d: t.getUTCDate() };
};

// "Jul", or "mid Jan" when a date falls inside the month.
const monthName = ({ m, d }) => `${d >= 10 ? `${t("mid")} ` : ""}${t(MONTHS[m])}`;

function span(from, to) {
  const a = parts(from);
  if (to === "today") return `${monthName(a)} ${a.y} - ${t("today")}`;
  const b = parts(to);
  return a.y === b.y
    ? `${monthName(a)} - ${monthName(b)} ${b.y}`
    : `${monthName(a)} ${a.y} - ${monthName(b)} ${b.y}`;
}

const tickName = (d) => {
  const { m, d: day } = parts(d);
  return day === 1 ? t(MONTHS[m]) : `${day} ${t(MONTHS[m])}`;
};

// Every 1st of the month on the axis, plus the first day when it is not one.
function ticksOf(stage) {
  if (stage.ticks) return stage.ticks;
  const list = [];
  const a = parts(stage.from);
  if (a.d !== 1) list.push(stage.from);
  const end = dayOf(stage.to);
  for (let y = a.y, m = a.m + (a.d === 1 ? 0 : 1); ; m++) {
    const d = `${y + Math.floor(m / 12)}-${pad((m % 12) + 1)}`;
    if (dayOf(d) > end) break;
    list.push(d);
  }
  return list;
}

const pct = (n) => `${(n * 100).toFixed(2)}%`;

function renderStage(stage, i) {
  const t0 = dayOf(stage.from);
  const len = dayOf(stage.to) - t0;
  const at = (d) => Math.min(1, Math.max(0, (dayOf(d) - t0) / len));

  const point = (pt) => {
    const project = pt.project && projects.find((x) => x.id === pt.project);
    const href = project
      ? `code/${project.id}.html`
      : pt.repo
        ? GH + pt.repo
        : pt.href;
    const external = /^https?:/.test(href);
    const when =
      pt.at === "today" ? t("today") : `${tickName(pt.at)} ${parts(pt.at).y}`;
    return `
      <a class="gantt-point${external ? "" : " gantt-point--here"}" style="--x: ${pct(at(pt.at))}" data-x="${at(pt.at)}"
        href="${href}"${external ? ' target="_blank" rel="noopener"' : ""} title="${t(pt.label)} · ${when}">
        <span class="gantt-label">${pt.label}${external ? " ↗" : ""}</span></a>`;
  };

  const track = (tr) => `
    <li class="gantt-row${tr.to === "today" ? " gantt-row--live" : ""}">
      <span class="gantt-name">${tr.name}</span>
      <div class="gantt-track" style="--rows: ${tr.points?.length ? 1 : 0}">
        <span class="gantt-bar" style="--a: ${pct(at(tr.from))}; --b: ${pct(at(tr.to))}"></span>
        ${(tr.points ?? []).map(point).join("")}
      </div>
    </li>`;

  const ticks = ticksOf(stage);
  return `
    <li class="stage">
      <div class="stage-head">
        <span class="stage-index">${pad(i + 1)}</span>
        <h3 class="stage-title">${stage.title}</h3>
        <span class="stage-when">${span(stage.from, stage.to)}</span>
        ${stage.link ? ext(stage.link, "the course ↗") : ""}
      </div>
      <div class="stage-text">${paras(stage.text)}</div>
      <div class="gantt">
        <div class="gantt-axis" aria-hidden="true">${ticks
          .map(
            (d) =>
              `<span class="gantt-tick${at(d) > 0.97 ? " gantt-tick--end" : ""}" style="--x: ${pct(at(d))}">${tickName(d)}</span>`,
          )
          .join(
            "",
          )}${stage.to === "today" ? `<span class="gantt-tick gantt-tick--end" style="--x: 100%">today</span>` : ""}</div>
        <div class="gantt-lines" aria-hidden="true">${ticks
          .map((d) => `<span style="--x: ${pct(at(d))}"></span>`)
          .join("")}</div>
        <ul class="gantt-rows">${stage.tracks.map(track).join("")}</ul>
      </div>
    </li>`;
}

const pathSection = () => `
  <ol class="path">
    ${path.map(renderStage).join("")}
    <li class="stage stage--next">
      <div class="stage-head">
        <span class="stage-index">${pad(path.length + 1)}</span>
        <h3 class="stage-title">Coming soon</h3>
      </div>
      <div class="stage-text"><p>${nextUp.text}</p></div>
      <ul class="next-up">${nextUp.courses.map((c) => `<li>${c}</li>`).join("")}</ul>
    </li>
  </ol>`;

function renderCode(main) {
  const apps = projects.filter((p) => !p.practice);
  const practice = projects.filter((p) => p.practice);
  main.innerHTML = `
    <section class="zone zone--page">
      <div class="shell">
        ${crumbs([["Résumé", "index.html"], ["Code"]])}
        ${zoneHead({ ...codeIntro, stacked: true })}
      </div>

      <section class="work">
        <div class="shell">
          ${head("Projects", `${count(apps.length, "apps & games")} · ${t("one page each")}`)}

          <div class="entries entries--pages">${apps.map(appCard).join("")}</div>

          <div class="practice">
            ${head("Practice", `${count(practice.length, "exercises")} · ${t("algorithms & data structures")}`)}
            <p class="practice-note">
              Smaller builds from the curriculum: a data structure or an algorithm written from scratch, each with an interface to play with.
            </p>
          </div>
          <div class="work-grid work-grid--practice">
            ${practice.map(card).join("")}
            ${ext(
              GH,
              `<span class="tile-arrow" aria-hidden="true">↗</span>
              <span class="tile-title">More on GitHub</span>
              <span class="tile-meta">All repositories</span>`,
              "tile frame",
            )}
          </div>
        </div>
      </section>

      <section class="timeline-block">
        <div class="shell">
          ${head("The path so far", `${span(path[0].from, "today")}`)}
          ${pathSection()}
        </div>
      </section>

      <section class="toolbox">
        <div class="shell">
          ${head("Toolbox", "what the work above runs on")}
          <dl class="tool-grid">
            ${toolbox.map(([k, v]) => `<div class="tool"><dt>${k}</dt><dd>${v}</dd></div>`).join("")}
          </dl>
        </div>
      </section>

      <div class="shell">${pager("code.html", "")}</div>
    </section>`;
}

function renderCodeProject(main, id) {
  const p = projects.find((x) => x.id === id);
  if (!p) return;
  const screens = screensOf(p);

  main.innerHTML = `
    <article class="zone zone--page">
      <div class="shell">
        ${crumbs([["Résumé", "../index.html"], ["Code", "../code.html"], [p.title]])}
        <header class="project-head">
          <div class="project-title-row">
            ${marks[p.id] ? `<img class="project-mark" src="${marks[p.id]}" alt="" />` : ""}
            <h1 class="project-title">${p.title}</h1>
          </div>
          <p class="project-tagline">${p.tagline}</p>
          <p class="project-lead">${p.lead}</p>
          <div class="project-actions">
            ${p.live ? ext(p.live, "Open the live version ↗", "button") : ""}
            ${ext(p.repo, "Read the code ↗", "button")}
          </div>
        </header>

        <section class="series-block">
          ${head("Screens", `${count(screens.length, "screens")}`)}
          ${gallery(screens, { label: p.title })}
        </section>

        <div class="project-grid">
          <div>
            ${p.notes.map(([h, t]) => `<section class="note"><h2>${h}</h2><p>${t}</p></section>`).join("")}
          </div>
          <aside class="project-side frame">
            ${
              p.shows
                ? `<h2 class="side-title">What it shows</h2>
            <ul class="shows">${p.shows.map((x) => `<li>${x}</li>`).join("")}</ul>`
                : ""
            }
            <h2 class="side-title">Built with</h2>
            <ul class="chips">${p.stack.map((s) => `<li class="chip">${s}</li>`).join("")}</ul>
            <h2 class="side-title">Links</h2>
            <ul class="link-col">
              <li>${ext(p.repo, "Repository ↗")}</li>
              ${p.live ? `<li>${ext(p.live, "Live version ↗")}</li>` : ""}
            </ul>
          </aside>
        </div>

        ${pager(`code/${p.id}.html`, "../")}
      </div>
    </article>`;
}

const VIEWS = {
  art: renderArt,
  series: renderSeries,
  code: renderCode,
  "code-project": renderCodeProject,
};

/* A collection can paint names in their own colours (`names`), wherever they
   appear on its page. Run after translation, so the dictionary only ever
   sees plain text. */
export function paintNames() {
  const main = document.querySelector('main[data-view="series"]');
  const names = main && series[main.dataset.id]?.names;
  if (!names) return;
  const find = new RegExp(`\\b(${Object.keys(names).join("|")})\\b`);
  const walker = document.createTreeWalker(main, NodeFilter.SHOW_TEXT);
  const hits = [];
  while (walker.nextNode()) if (find.test(walker.currentNode.data)) hits.push(walker.currentNode);
  // A heading that is only the name takes the colour itself, so it can still
  // be typed in letter by letter. Otherwise every odd part is a name.
  for (const node of hits) {
    const whole = names[node.data.trim()];
    if (whole && node.parentElement.childNodes.length === 1) {
      node.parentElement.classList.add("name");
      node.parentElement.style.setProperty("--c", whole);
      continue;
    }
    const parts = node.data.split(new RegExp(find, "g"));
    node.replaceWith(
      ...parts.map((part, i) =>
        i % 2 ? Object.assign(document.createElement("span"), { className: "name", textContent: part, style: `--c: ${names[part]}` }) : part,
      ),
    );
  }
}

// The home's tiles take their page's colour, and an art tile its crop, from
// the content, like the pages.
function tintTiles() {
  for (const tile of document.querySelectorAll(".work-tile")) {
    const [, section, id] = tile.getAttribute("href").match(/(art|code)\/([\w-]+)\.html/) ?? [];
    const { hue, coverPos } = (section === "art" ? series[id] : projects.find((p) => p.id === id)) ?? {};
    if (hue) tile.style.setProperty("--hue", hue);
    if (coverPos) tile.querySelector("img").style.objectPosition = coverPos;
  }
}

export function renderPage() {
  tintTiles();
  const main = document.querySelector("main[data-view]");
  if (main) VIEWS[main.dataset.view]?.(main, main.dataset.id);

  // The page was empty when the browser looked for #anchor; look again.
  if (main && location.hash)
    document.getElementById(location.hash.slice(1))?.scrollIntoView();
}
